package ydb_go_genproto

//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_discovery.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_operation.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_status_codes.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_export.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_query_stats.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_table.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_import.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_rate_limiter.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_value.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_common.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_issue_message.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_scheme.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_monitoring.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_scripting.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_rate_limiter.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_coordination.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_experimental.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_persqueue_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/protos/ydb_persqueue_cluster_discovery.proto

//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_discovery_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_export_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_import_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_monitoring_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_operation_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_rate_limiter_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_scheme_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_scripting_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_table_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_rate_limiter_v1.proto
//go:generate protoc --go_out=. --go_opt=module=github.com/YandexDatabase/ydb-go-genproto --go-grpc_out=. --go-grpc_opt=module=github.com/YandexDatabase/ydb-go-genproto -Iapi -Iapi/protos -Iapi/protos/validation api/ydb_coordination_v1.proto
