// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: draft/protos/ydb_object_storage.proto

package Ydb_ObjectStorage

import (
	Ydb "github.com/ydb-platform/ydb-go-genproto/protos/Ydb"
	Ydb_Issue "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Issue"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListingRequest_EMatchType int32

const (
	ListingRequest_EQUAL     ListingRequest_EMatchType = 0
	ListingRequest_NOT_EQUAL ListingRequest_EMatchType = 1
)

// Enum value maps for ListingRequest_EMatchType.
var (
	ListingRequest_EMatchType_name = map[int32]string{
		0: "EQUAL",
		1: "NOT_EQUAL",
	}
	ListingRequest_EMatchType_value = map[string]int32{
		"EQUAL":     0,
		"NOT_EQUAL": 1,
	}
)

func (x ListingRequest_EMatchType) Enum() *ListingRequest_EMatchType {
	p := new(ListingRequest_EMatchType)
	*p = x
	return p
}

func (x ListingRequest_EMatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListingRequest_EMatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_draft_protos_ydb_object_storage_proto_enumTypes[0].Descriptor()
}

func (ListingRequest_EMatchType) Type() protoreflect.EnumType {
	return &file_draft_protos_ydb_object_storage_proto_enumTypes[0]
}

func (x ListingRequest_EMatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListingRequest_EMatchType.Descriptor instead.
func (ListingRequest_EMatchType) EnumDescriptor() ([]byte, []int) {
	return file_draft_protos_ydb_object_storage_proto_rawDescGZIP(), []int{0, 0}
}

type ListingRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TableName           string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	KeyPrefix           *Ydb.TypedValue        `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"` // A tuple representing all key columns that preceed path column
	PathColumnPrefix    string                 `protobuf:"bytes,3,opt,name=path_column_prefix,json=pathColumnPrefix,proto3" json:"path_column_prefix,omitempty"`
	PathColumnDelimiter string                 `protobuf:"bytes,4,opt,name=path_column_delimiter,json=pathColumnDelimiter,proto3" json:"path_column_delimiter,omitempty"`
	ContinuationToken   []byte                 `protobuf:"bytes,5,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	StartAfterKeySuffix *Ydb.TypedValue        `protobuf:"bytes,6,opt,name=start_after_key_suffix,json=startAfterKeySuffix,proto3" json:"start_after_key_suffix,omitempty"` // A tuple representing key columns that succeed path column
	MaxKeys             int32                  `protobuf:"varint,7,opt,name=max_keys,json=maxKeys,proto3" json:"max_keys,omitempty"`
	ColumnsToReturn     []string               `protobuf:"bytes,8,rep,name=columns_to_return,json=columnsToReturn,proto3" json:"columns_to_return,omitempty"`
	MatchingFilter      *Ydb.TypedValue        `protobuf:"bytes,10,opt,name=matching_filter,json=matchingFilter,proto3" json:"matching_filter,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListingRequest) Reset() {
	*x = ListingRequest{}
	mi := &file_draft_protos_ydb_object_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingRequest) ProtoMessage() {}

func (x *ListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_object_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingRequest.ProtoReflect.Descriptor instead.
func (*ListingRequest) Descriptor() ([]byte, []int) {
	return file_draft_protos_ydb_object_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ListingRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListingRequest) GetKeyPrefix() *Ydb.TypedValue {
	if x != nil {
		return x.KeyPrefix
	}
	return nil
}

func (x *ListingRequest) GetPathColumnPrefix() string {
	if x != nil {
		return x.PathColumnPrefix
	}
	return ""
}

func (x *ListingRequest) GetPathColumnDelimiter() string {
	if x != nil {
		return x.PathColumnDelimiter
	}
	return ""
}

func (x *ListingRequest) GetContinuationToken() []byte {
	if x != nil {
		return x.ContinuationToken
	}
	return nil
}

func (x *ListingRequest) GetStartAfterKeySuffix() *Ydb.TypedValue {
	if x != nil {
		return x.StartAfterKeySuffix
	}
	return nil
}

func (x *ListingRequest) GetMaxKeys() int32 {
	if x != nil {
		return x.MaxKeys
	}
	return 0
}

func (x *ListingRequest) GetColumnsToReturn() []string {
	if x != nil {
		return x.ColumnsToReturn
	}
	return nil
}

func (x *ListingRequest) GetMatchingFilter() *Ydb.TypedValue {
	if x != nil {
		return x.MatchingFilter
	}
	return nil
}

type ListingResponse struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	Status                Ydb.StatusIds_StatusCode  `protobuf:"varint,1,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues                []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	CommonPrefixes        []string                  `protobuf:"bytes,3,rep,name=common_prefixes,json=commonPrefixes,proto3" json:"common_prefixes,omitempty"` // Folders.
	Contents              *Ydb.ResultSet            `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`                                   // Every Contents row starts with key suffix with KeySuffixSize columns
	IsTruncated           bool                      `protobuf:"varint,5,opt,name=is_truncated,json=isTruncated,proto3" json:"is_truncated,omitempty"`
	NextContinuationToken []byte                    `protobuf:"bytes,6,opt,name=next_continuation_token,json=nextContinuationToken,proto3" json:"next_continuation_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListingResponse) Reset() {
	*x = ListingResponse{}
	mi := &file_draft_protos_ydb_object_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingResponse) ProtoMessage() {}

func (x *ListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_object_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingResponse.ProtoReflect.Descriptor instead.
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return file_draft_protos_ydb_object_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ListingResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil {
		return x.Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *ListingResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListingResponse) GetCommonPrefixes() []string {
	if x != nil {
		return x.CommonPrefixes
	}
	return nil
}

func (x *ListingResponse) GetContents() *Ydb.ResultSet {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ListingResponse) GetIsTruncated() bool {
	if x != nil {
		return x.IsTruncated
	}
	return false
}

func (x *ListingResponse) GetNextContinuationToken() []byte {
	if x != nil {
		return x.NextContinuationToken
	}
	return nil
}

var File_draft_protos_ydb_object_storage_proto protoreflect.FileDescriptor

const file_draft_protos_ydb_object_storage_proto_rawDesc = "" +
	"\n" +
	"%draft/protos/ydb_object_storage.proto\x12\x11Ydb.ObjectStorage\x1a\x1eprotos/ydb_issue_message.proto\x1a\x16protos/ydb_value.proto\x1a\x1dprotos/ydb_status_codes.proto\"\xe5\x03\n" +
	"\x0eListingRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12.\n" +
	"\n" +
	"key_prefix\x18\x02 \x01(\v2\x0f.Ydb.TypedValueR\tkeyPrefix\x12,\n" +
	"\x12path_column_prefix\x18\x03 \x01(\tR\x10pathColumnPrefix\x122\n" +
	"\x15path_column_delimiter\x18\x04 \x01(\tR\x13pathColumnDelimiter\x12-\n" +
	"\x12continuation_token\x18\x05 \x01(\fR\x11continuationToken\x12D\n" +
	"\x16start_after_key_suffix\x18\x06 \x01(\v2\x0f.Ydb.TypedValueR\x13startAfterKeySuffix\x12\x19\n" +
	"\bmax_keys\x18\a \x01(\x05R\amaxKeys\x12*\n" +
	"\x11columns_to_return\x18\b \x03(\tR\x0fcolumnsToReturn\x128\n" +
	"\x0fmatching_filter\x18\n" +
	" \x01(\v2\x0f.Ydb.TypedValueR\x0ematchingFilter\"&\n" +
	"\n" +
	"EMatchType\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\r\n" +
	"\tNOT_EQUAL\x10\x01J\x04\b\t\x10\n" +
	"\"\xa5\x02\n" +
	"\x0fListingResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.Ydb.Issue.IssueMessageR\x06issues\x12'\n" +
	"\x0fcommon_prefixes\x18\x03 \x03(\tR\x0ecommonPrefixes\x12*\n" +
	"\bcontents\x18\x04 \x01(\v2\x0e.Ydb.ResultSetR\bcontents\x12!\n" +
	"\fis_truncated\x18\x05 \x01(\bR\visTruncated\x126\n" +
	"\x17next_continuation_token\x18\x06 \x01(\fR\x15nextContinuationTokenBp\n" +
	"#tech.ydb.proto.draft.object_storageZFgithub.com/ydb-platform/ydb-go-genproto/draft/protos/Ydb_ObjectStorage\xf8\x01\x01b\x06proto3"

var (
	file_draft_protos_ydb_object_storage_proto_rawDescOnce sync.Once
	file_draft_protos_ydb_object_storage_proto_rawDescData []byte
)

func file_draft_protos_ydb_object_storage_proto_rawDescGZIP() []byte {
	file_draft_protos_ydb_object_storage_proto_rawDescOnce.Do(func() {
		file_draft_protos_ydb_object_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draft_protos_ydb_object_storage_proto_rawDesc), len(file_draft_protos_ydb_object_storage_proto_rawDesc)))
	})
	return file_draft_protos_ydb_object_storage_proto_rawDescData
}

var file_draft_protos_ydb_object_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_draft_protos_ydb_object_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_draft_protos_ydb_object_storage_proto_goTypes = []any{
	(ListingRequest_EMatchType)(0), // 0: Ydb.ObjectStorage.ListingRequest.EMatchType
	(*ListingRequest)(nil),         // 1: Ydb.ObjectStorage.ListingRequest
	(*ListingResponse)(nil),        // 2: Ydb.ObjectStorage.ListingResponse
	(*Ydb.TypedValue)(nil),         // 3: Ydb.TypedValue
	(Ydb.StatusIds_StatusCode)(0),  // 4: Ydb.StatusIds.StatusCode
	(*Ydb_Issue.IssueMessage)(nil), // 5: Ydb.Issue.IssueMessage
	(*Ydb.ResultSet)(nil),          // 6: Ydb.ResultSet
}
var file_draft_protos_ydb_object_storage_proto_depIdxs = []int32{
	3, // 0: Ydb.ObjectStorage.ListingRequest.key_prefix:type_name -> Ydb.TypedValue
	3, // 1: Ydb.ObjectStorage.ListingRequest.start_after_key_suffix:type_name -> Ydb.TypedValue
	3, // 2: Ydb.ObjectStorage.ListingRequest.matching_filter:type_name -> Ydb.TypedValue
	4, // 3: Ydb.ObjectStorage.ListingResponse.status:type_name -> Ydb.StatusIds.StatusCode
	5, // 4: Ydb.ObjectStorage.ListingResponse.issues:type_name -> Ydb.Issue.IssueMessage
	6, // 5: Ydb.ObjectStorage.ListingResponse.contents:type_name -> Ydb.ResultSet
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_draft_protos_ydb_object_storage_proto_init() }
func file_draft_protos_ydb_object_storage_proto_init() {
	if File_draft_protos_ydb_object_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draft_protos_ydb_object_storage_proto_rawDesc), len(file_draft_protos_ydb_object_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draft_protos_ydb_object_storage_proto_goTypes,
		DependencyIndexes: file_draft_protos_ydb_object_storage_proto_depIdxs,
		EnumInfos:         file_draft_protos_ydb_object_storage_proto_enumTypes,
		MessageInfos:      file_draft_protos_ydb_object_storage_proto_msgTypes,
	}.Build()
	File_draft_protos_ydb_object_storage_proto = out.File
	file_draft_protos_ydb_object_storage_proto_goTypes = nil
	file_draft_protos_ydb_object_storage_proto_depIdxs = nil
}
