// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/ydb_operation.proto

//go:build !protoopaque

package Ydb_Operations

import (
	Ydb "github.com/ydb-platform/ydb-go-genproto/protos/Ydb"
	Ydb_Issue "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Issue"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationParams_OperationMode int32

const (
	OperationParams_OPERATION_MODE_UNSPECIFIED OperationParams_OperationMode = 0
	// Server will only reply once operation is finished (ready=true), and operation object won't be
	// accessible after the reply. This is a basic request-response mode.
	OperationParams_SYNC  OperationParams_OperationMode = 1
	OperationParams_ASYNC OperationParams_OperationMode = 2
)

// Enum value maps for OperationParams_OperationMode.
var (
	OperationParams_OperationMode_name = map[int32]string{
		0: "OPERATION_MODE_UNSPECIFIED",
		1: "SYNC",
		2: "ASYNC",
	}
	OperationParams_OperationMode_value = map[string]int32{
		"OPERATION_MODE_UNSPECIFIED": 0,
		"SYNC":                       1,
		"ASYNC":                      2,
	}
)

func (x OperationParams_OperationMode) Enum() *OperationParams_OperationMode {
	p := new(OperationParams_OperationMode)
	*p = x
	return p
}

func (x OperationParams_OperationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationParams_OperationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ydb_operation_proto_enumTypes[0].Descriptor()
}

func (OperationParams_OperationMode) Type() protoreflect.EnumType {
	return &file_protos_ydb_operation_proto_enumTypes[0]
}

func (x OperationParams_OperationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OperationParams struct {
	state         protoimpl.MessageState         `protogen:"hybrid.v1"`
	OperationMode *OperationParams_OperationMode `protobuf:"varint,1,opt,name=operation_mode,json=operationMode,enum=Ydb.Operations.OperationParams_OperationMode" json:"operation_mode,omitempty"`
	// Indicates that client is no longer interested in the result of operation after the specified duration
	// starting from the time operation arrives at the server.
	// Server will try to stop the execution of operation and if no result is currently available the operation
	// will receive TIMEOUT status code, which will be sent back to client if it was waiting for the operation result.
	// Timeout of operation does not tell anything about its result, it might be completed successfully
	// or cancelled on server.
	OperationTimeout *durationpb.Duration `protobuf:"bytes,2,opt,name=operation_timeout,json=operationTimeout" json:"operation_timeout,omitempty"`
	// Server will try to cancel the operation after the specified duration starting from the time
	// the operation arrives at server.
	// In case of successful cancellation operation will receive CANCELLED status code, which will be
	// sent back to client if it was waiting for the operation result.
	// In case when cancellation isn't possible, no action will be performed.
	CancelAfter *durationpb.Duration `protobuf:"bytes,3,opt,name=cancel_after,json=cancelAfter" json:"cancel_after,omitempty"`
	// User-defined labels of operation.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If enabled, server will report cost information, if supported by the operation.
	// This flag is mostly useful for SYNC operations, to get the cost information in the response.
	ReportCostInfo *Ydb.FeatureFlag_Status `protobuf:"varint,5,opt,name=report_cost_info,json=reportCostInfo,enum=Ydb.FeatureFlag_Status" json:"report_cost_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationParams) Reset() {
	*x = OperationParams{}
	mi := &file_protos_ydb_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationParams) ProtoMessage() {}

func (x *OperationParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperationParams) GetOperationMode() OperationParams_OperationMode {
	if x != nil && x.OperationMode != nil {
		return *x.OperationMode
	}
	return OperationParams_OPERATION_MODE_UNSPECIFIED
}

func (x *OperationParams) GetOperationTimeout() *durationpb.Duration {
	if x != nil {
		return x.OperationTimeout
	}
	return nil
}

func (x *OperationParams) GetCancelAfter() *durationpb.Duration {
	if x != nil {
		return x.CancelAfter
	}
	return nil
}

func (x *OperationParams) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *OperationParams) GetReportCostInfo() Ydb.FeatureFlag_Status {
	if x != nil && x.ReportCostInfo != nil {
		return *x.ReportCostInfo
	}
	return Ydb.FeatureFlag_Status(0)
}

func (x *OperationParams) SetOperationMode(v OperationParams_OperationMode) {
	x.OperationMode = &v
}

func (x *OperationParams) SetOperationTimeout(v *durationpb.Duration) {
	x.OperationTimeout = v
}

func (x *OperationParams) SetCancelAfter(v *durationpb.Duration) {
	x.CancelAfter = v
}

func (x *OperationParams) SetLabels(v map[string]string) {
	x.Labels = v
}

func (x *OperationParams) SetReportCostInfo(v Ydb.FeatureFlag_Status) {
	x.ReportCostInfo = &v
}

func (x *OperationParams) HasOperationMode() bool {
	if x == nil {
		return false
	}
	return x.OperationMode != nil
}

func (x *OperationParams) HasOperationTimeout() bool {
	if x == nil {
		return false
	}
	return x.OperationTimeout != nil
}

func (x *OperationParams) HasCancelAfter() bool {
	if x == nil {
		return false
	}
	return x.CancelAfter != nil
}

func (x *OperationParams) HasReportCostInfo() bool {
	if x == nil {
		return false
	}
	return x.ReportCostInfo != nil
}

func (x *OperationParams) ClearOperationMode() {
	x.OperationMode = nil
}

func (x *OperationParams) ClearOperationTimeout() {
	x.OperationTimeout = nil
}

func (x *OperationParams) ClearCancelAfter() {
	x.CancelAfter = nil
}

func (x *OperationParams) ClearReportCostInfo() {
	x.ReportCostInfo = nil
}

type OperationParams_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationMode *OperationParams_OperationMode
	// Indicates that client is no longer interested in the result of operation after the specified duration
	// starting from the time operation arrives at the server.
	// Server will try to stop the execution of operation and if no result is currently available the operation
	// will receive TIMEOUT status code, which will be sent back to client if it was waiting for the operation result.
	// Timeout of operation does not tell anything about its result, it might be completed successfully
	// or cancelled on server.
	OperationTimeout *durationpb.Duration
	// Server will try to cancel the operation after the specified duration starting from the time
	// the operation arrives at server.
	// In case of successful cancellation operation will receive CANCELLED status code, which will be
	// sent back to client if it was waiting for the operation result.
	// In case when cancellation isn't possible, no action will be performed.
	CancelAfter *durationpb.Duration
	// User-defined labels of operation.
	Labels map[string]string
	// If enabled, server will report cost information, if supported by the operation.
	// This flag is mostly useful for SYNC operations, to get the cost information in the response.
	ReportCostInfo *Ydb.FeatureFlag_Status
}

func (b0 OperationParams_builder) Build() *OperationParams {
	m0 := &OperationParams{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationMode = b.OperationMode
	x.OperationTimeout = b.OperationTimeout
	x.CancelAfter = b.CancelAfter
	x.Labels = b.Labels
	x.ReportCostInfo = b.ReportCostInfo
	return m0
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_protos_ydb_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOperationRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GetOperationRequest) SetId(v string) {
	x.Id = &v
}

func (x *GetOperationRequest) HasId() bool {
	if x == nil {
		return false
	}
	return x.Id != nil
}

func (x *GetOperationRequest) ClearId() {
	x.Id = nil
}

type GetOperationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetOperationRequest_builder) Build() *GetOperationRequest {
	m0 := &GetOperationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_protos_ydb_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *GetOperationResponse) SetOperation(v *Operation) {
	x.Operation = v
}

func (x *GetOperationResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *GetOperationResponse) ClearOperation() {
	x.Operation = nil
}

type GetOperationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Operation *Operation
}

func (b0 GetOperationResponse_builder) Build() *GetOperationResponse {
	m0 := &GetOperationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_protos_ydb_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CancelOperationRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CancelOperationRequest) SetId(v string) {
	x.Id = &v
}

func (x *CancelOperationRequest) HasId() bool {
	if x == nil {
		return false
	}
	return x.Id != nil
}

func (x *CancelOperationRequest) ClearId() {
	x.Id = nil
}

type CancelOperationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 CancelOperationRequest_builder) Build() *CancelOperationRequest {
	m0 := &CancelOperationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type CancelOperationResponse struct {
	state         protoimpl.MessageState    `protogen:"hybrid.v1"`
	Status        *Ydb.StatusIds_StatusCode `protobuf:"varint,1,opt,name=status,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues        []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationResponse) Reset() {
	*x = CancelOperationResponse{}
	mi := &file_protos_ydb_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationResponse) ProtoMessage() {}

func (x *CancelOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CancelOperationResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *CancelOperationResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *CancelOperationResponse) SetStatus(v Ydb.StatusIds_StatusCode) {
	x.Status = &v
}

func (x *CancelOperationResponse) SetIssues(v []*Ydb_Issue.IssueMessage) {
	x.Issues = v
}

func (x *CancelOperationResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *CancelOperationResponse) ClearStatus() {
	x.Status = nil
}

type CancelOperationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *Ydb.StatusIds_StatusCode
	Issues []*Ydb_Issue.IssueMessage
}

func (b0 CancelOperationResponse_builder) Build() *CancelOperationResponse {
	m0 := &CancelOperationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	x.Issues = b.Issues
	return m0
}

type ForgetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetOperationRequest) Reset() {
	*x = ForgetOperationRequest{}
	mi := &file_protos_ydb_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetOperationRequest) ProtoMessage() {}

func (x *ForgetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForgetOperationRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ForgetOperationRequest) SetId(v string) {
	x.Id = &v
}

func (x *ForgetOperationRequest) HasId() bool {
	if x == nil {
		return false
	}
	return x.Id != nil
}

func (x *ForgetOperationRequest) ClearId() {
	x.Id = nil
}

type ForgetOperationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 ForgetOperationRequest_builder) Build() *ForgetOperationRequest {
	m0 := &ForgetOperationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type ForgetOperationResponse struct {
	state         protoimpl.MessageState    `protogen:"hybrid.v1"`
	Status        *Ydb.StatusIds_StatusCode `protobuf:"varint,1,opt,name=status,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues        []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetOperationResponse) Reset() {
	*x = ForgetOperationResponse{}
	mi := &file_protos_ydb_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetOperationResponse) ProtoMessage() {}

func (x *ForgetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForgetOperationResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *ForgetOperationResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ForgetOperationResponse) SetStatus(v Ydb.StatusIds_StatusCode) {
	x.Status = &v
}

func (x *ForgetOperationResponse) SetIssues(v []*Ydb_Issue.IssueMessage) {
	x.Issues = v
}

func (x *ForgetOperationResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ForgetOperationResponse) ClearStatus() {
	x.Status = nil
}

type ForgetOperationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *Ydb.StatusIds_StatusCode
	Issues []*Ydb_Issue.IssueMessage
}

func (b0 ForgetOperationResponse_builder) Build() *ForgetOperationResponse {
	m0 := &ForgetOperationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	x.Issues = b.Issues
	return m0
}

type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Kind          *string                `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	PageSize      *uint64                `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_protos_ydb_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListOperationsRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *ListOperationsRequest) GetPageSize() uint64 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOperationsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListOperationsRequest) SetKind(v string) {
	x.Kind = &v
}

func (x *ListOperationsRequest) SetPageSize(v uint64) {
	x.PageSize = &v
}

func (x *ListOperationsRequest) SetPageToken(v string) {
	x.PageToken = &v
}

func (x *ListOperationsRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return x.Kind != nil
}

func (x *ListOperationsRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return x.PageSize != nil
}

func (x *ListOperationsRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return x.PageToken != nil
}

func (x *ListOperationsRequest) ClearKind() {
	x.Kind = nil
}

func (x *ListOperationsRequest) ClearPageSize() {
	x.PageSize = nil
}

func (x *ListOperationsRequest) ClearPageToken() {
	x.PageToken = nil
}

type ListOperationsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kind      *string
	PageSize  *uint64
	PageToken *string
}

func (b0 ListOperationsRequest_builder) Build() *ListOperationsRequest {
	m0 := &ListOperationsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Kind = b.Kind
	x.PageSize = b.PageSize
	x.PageToken = b.PageToken
	return m0
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState    `protogen:"hybrid.v1"`
	Status        *Ydb.StatusIds_StatusCode `protobuf:"varint,1,opt,name=status,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues        []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	Operations    []*Operation              `protobuf:"bytes,3,rep,name=operations" json:"operations,omitempty"`
	NextPageToken *string                   `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_protos_ydb_operation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListOperationsResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *ListOperationsResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *ListOperationsResponse) SetStatus(v Ydb.StatusIds_StatusCode) {
	x.Status = &v
}

func (x *ListOperationsResponse) SetIssues(v []*Ydb_Issue.IssueMessage) {
	x.Issues = v
}

func (x *ListOperationsResponse) SetOperations(v []*Operation) {
	x.Operations = v
}

func (x *ListOperationsResponse) SetNextPageToken(v string) {
	x.NextPageToken = &v
}

func (x *ListOperationsResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ListOperationsResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return x.NextPageToken != nil
}

func (x *ListOperationsResponse) ClearStatus() {
	x.Status = nil
}

func (x *ListOperationsResponse) ClearNextPageToken() {
	x.NextPageToken = nil
}

type ListOperationsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status        *Ydb.StatusIds_StatusCode
	Issues        []*Ydb_Issue.IssueMessage
	Operations    []*Operation
	NextPageToken *string
}

func (b0 ListOperationsResponse_builder) Build() *ListOperationsResponse {
	m0 := &ListOperationsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Status = b.Status
	x.Issues = b.Issues
	x.Operations = b.Operations
	x.NextPageToken = b.NextPageToken
	return m0
}

type Operation struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Identifier of the operation, empty value means no active operation object is present (it was forgotten or
	// not created in the first place, as in SYNC operation mode).
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// true - this operation has beed finished (doesn't matter successful or not),
	// so Status field has status code, and Result field can contains result data.
	// false - this operation still running. You can repeat request using operation Id.
	Ready  *bool                     `protobuf:"varint,2,opt,name=ready" json:"ready,omitempty"`
	Status *Ydb.StatusIds_StatusCode `protobuf:"varint,3,opt,name=status,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues []*Ydb_Issue.IssueMessage `protobuf:"bytes,4,rep,name=issues" json:"issues,omitempty"`
	// Result data
	Result   *anypb.Any `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"`
	Metadata *anypb.Any `protobuf:"bytes,6,opt,name=metadata" json:"metadata,omitempty"`
	// Contains information about the cost of the operation.
	// For completed operations, it shows the final cost of the operation.
	// For operations in progress, it might indicate the current cost of the operation (if supported).
	CostInfo      *Ydb.CostInfo `protobuf:"bytes,7,opt,name=cost_info,json=costInfo" json:"cost_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_protos_ydb_operation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_operation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Operation) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Operation) GetReady() bool {
	if x != nil && x.Ready != nil {
		return *x.Ready
	}
	return false
}

func (x *Operation) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *Operation) GetIssues() []*Ydb_Issue.IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *Operation) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Operation) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Operation) GetCostInfo() *Ydb.CostInfo {
	if x != nil {
		return x.CostInfo
	}
	return nil
}

func (x *Operation) SetId(v string) {
	x.Id = &v
}

func (x *Operation) SetReady(v bool) {
	x.Ready = &v
}

func (x *Operation) SetStatus(v Ydb.StatusIds_StatusCode) {
	x.Status = &v
}

func (x *Operation) SetIssues(v []*Ydb_Issue.IssueMessage) {
	x.Issues = v
}

func (x *Operation) SetResult(v *anypb.Any) {
	x.Result = v
}

func (x *Operation) SetMetadata(v *anypb.Any) {
	x.Metadata = v
}

func (x *Operation) SetCostInfo(v *Ydb.CostInfo) {
	x.CostInfo = v
}

func (x *Operation) HasId() bool {
	if x == nil {
		return false
	}
	return x.Id != nil
}

func (x *Operation) HasReady() bool {
	if x == nil {
		return false
	}
	return x.Ready != nil
}

func (x *Operation) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *Operation) HasResult() bool {
	if x == nil {
		return false
	}
	return x.Result != nil
}

func (x *Operation) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Operation) HasCostInfo() bool {
	if x == nil {
		return false
	}
	return x.CostInfo != nil
}

func (x *Operation) ClearId() {
	x.Id = nil
}

func (x *Operation) ClearReady() {
	x.Ready = nil
}

func (x *Operation) ClearStatus() {
	x.Status = nil
}

func (x *Operation) ClearResult() {
	x.Result = nil
}

func (x *Operation) ClearMetadata() {
	x.Metadata = nil
}

func (x *Operation) ClearCostInfo() {
	x.CostInfo = nil
}

type Operation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Identifier of the operation, empty value means no active operation object is present (it was forgotten or
	// not created in the first place, as in SYNC operation mode).
	Id *string
	// true - this operation has beed finished (doesn't matter successful or not),
	// so Status field has status code, and Result field can contains result data.
	// false - this operation still running. You can repeat request using operation Id.
	Ready  *bool
	Status *Ydb.StatusIds_StatusCode
	Issues []*Ydb_Issue.IssueMessage
	// Result data
	Result   *anypb.Any
	Metadata *anypb.Any
	// Contains information about the cost of the operation.
	// For completed operations, it shows the final cost of the operation.
	// For operations in progress, it might indicate the current cost of the operation (if supported).
	CostInfo *Ydb.CostInfo
}

func (b0 Operation_builder) Build() *Operation {
	m0 := &Operation{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Ready = b.Ready
	x.Status = b.Status
	x.Issues = b.Issues
	x.Result = b.Result
	x.Metadata = b.Metadata
	x.CostInfo = b.CostInfo
	return m0
}

var File_protos_ydb_operation_proto protoreflect.FileDescriptor

const file_protos_ydb_operation_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/ydb_operation.proto\x12\x0eYdb.Operations\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a#protos/annotations/validation.proto\x1a\x17protos/ydb_common.proto\x1a\x1eprotos/ydb_issue_message.proto\x1a\x1dprotos/ydb_status_codes.proto\x1a!google/protobuf/go_features.proto\"\x88\x04\n" +
	"\x0fOperationParams\x12T\n" +
	"\x0eoperation_mode\x18\x01 \x01(\x0e2-.Ydb.Operations.OperationParams.OperationModeR\roperationMode\x12F\n" +
	"\x11operation_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10operationTimeout\x12<\n" +
	"\fcancel_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vcancelAfter\x12U\n" +
	"\x06labels\x18\x04 \x03(\v2+.Ydb.Operations.OperationParams.LabelsEntryB\x10\xa2\xe6*\x03\x18\x80\x01\xaa\xe6*\x05\n" +
	"\x03\x18\x80\x01R\x06labels\x12A\n" +
	"\x10report_cost_info\x18\x05 \x01(\x0e2\x17.Ydb.FeatureFlag.StatusR\x0ereportCostInfo\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\rOperationMode\x12\x1e\n" +
	"\x1aOPERATION_MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SYNC\x10\x01\x12\t\n" +
	"\x05ASYNC\x10\x02\"+\n" +
	"\x13GetOperationRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xe6*\x01R\x02id\"O\n" +
	"\x14GetOperationResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\".\n" +
	"\x16CancelOperationRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xe6*\x01R\x02id\"}\n" +
	"\x17CancelOperationResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.Ydb.Issue.IssueMessageR\x06issues\".\n" +
	"\x16ForgetOperationRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xe6*\x01R\x02id\"}\n" +
	"\x17ForgetOperationResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.Ydb.Issue.IssueMessageR\x06issues\"m\n" +
	"\x15ListOperationsRequest\x12\x18\n" +
	"\x04kind\x18\x01 \x01(\tB\x04\x90\xe6*\x01R\x04kind\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xdf\x01\n" +
	"\x16ListOperationsResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.Ydb.Issue.IssueMessageR\x06issues\x129\n" +
	"\n" +
	"operations\x18\x03 \x03(\v2\x19.Ydb.Operations.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x04 \x01(\tR\rnextPageToken\"\xa1\x02\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\x12/\n" +
	"\x06issues\x18\x04 \x03(\v2\x17.Ydb.Issue.IssueMessageR\x06issues\x12,\n" +
	"\x06result\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x06result\x120\n" +
	"\bmetadata\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\bmetadata\x12*\n" +
	"\tcost_info\x18\a \x01(\v2\r.Ydb.CostInfoR\bcostInfoBk\n" +
	"\x0etech.ydb.protoB\x0fOperationProtosZ=github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Operations\xf8\x01\x01\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_protos_ydb_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_ydb_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_ydb_operation_proto_goTypes = []any{
	(OperationParams_OperationMode)(0), // 0: Ydb.Operations.OperationParams.OperationMode
	(*OperationParams)(nil),            // 1: Ydb.Operations.OperationParams
	(*GetOperationRequest)(nil),        // 2: Ydb.Operations.GetOperationRequest
	(*GetOperationResponse)(nil),       // 3: Ydb.Operations.GetOperationResponse
	(*CancelOperationRequest)(nil),     // 4: Ydb.Operations.CancelOperationRequest
	(*CancelOperationResponse)(nil),    // 5: Ydb.Operations.CancelOperationResponse
	(*ForgetOperationRequest)(nil),     // 6: Ydb.Operations.ForgetOperationRequest
	(*ForgetOperationResponse)(nil),    // 7: Ydb.Operations.ForgetOperationResponse
	(*ListOperationsRequest)(nil),      // 8: Ydb.Operations.ListOperationsRequest
	(*ListOperationsResponse)(nil),     // 9: Ydb.Operations.ListOperationsResponse
	(*Operation)(nil),                  // 10: Ydb.Operations.Operation
	nil,                                // 11: Ydb.Operations.OperationParams.LabelsEntry
	(*durationpb.Duration)(nil),        // 12: google.protobuf.Duration
	(Ydb.FeatureFlag_Status)(0),        // 13: Ydb.FeatureFlag.Status
	(Ydb.StatusIds_StatusCode)(0),      // 14: Ydb.StatusIds.StatusCode
	(*Ydb_Issue.IssueMessage)(nil),     // 15: Ydb.Issue.IssueMessage
	(*anypb.Any)(nil),                  // 16: google.protobuf.Any
	(*Ydb.CostInfo)(nil),               // 17: Ydb.CostInfo
}
var file_protos_ydb_operation_proto_depIdxs = []int32{
	0,  // 0: Ydb.Operations.OperationParams.operation_mode:type_name -> Ydb.Operations.OperationParams.OperationMode
	12, // 1: Ydb.Operations.OperationParams.operation_timeout:type_name -> google.protobuf.Duration
	12, // 2: Ydb.Operations.OperationParams.cancel_after:type_name -> google.protobuf.Duration
	11, // 3: Ydb.Operations.OperationParams.labels:type_name -> Ydb.Operations.OperationParams.LabelsEntry
	13, // 4: Ydb.Operations.OperationParams.report_cost_info:type_name -> Ydb.FeatureFlag.Status
	10, // 5: Ydb.Operations.GetOperationResponse.operation:type_name -> Ydb.Operations.Operation
	14, // 6: Ydb.Operations.CancelOperationResponse.status:type_name -> Ydb.StatusIds.StatusCode
	15, // 7: Ydb.Operations.CancelOperationResponse.issues:type_name -> Ydb.Issue.IssueMessage
	14, // 8: Ydb.Operations.ForgetOperationResponse.status:type_name -> Ydb.StatusIds.StatusCode
	15, // 9: Ydb.Operations.ForgetOperationResponse.issues:type_name -> Ydb.Issue.IssueMessage
	14, // 10: Ydb.Operations.ListOperationsResponse.status:type_name -> Ydb.StatusIds.StatusCode
	15, // 11: Ydb.Operations.ListOperationsResponse.issues:type_name -> Ydb.Issue.IssueMessage
	10, // 12: Ydb.Operations.ListOperationsResponse.operations:type_name -> Ydb.Operations.Operation
	14, // 13: Ydb.Operations.Operation.status:type_name -> Ydb.StatusIds.StatusCode
	15, // 14: Ydb.Operations.Operation.issues:type_name -> Ydb.Issue.IssueMessage
	16, // 15: Ydb.Operations.Operation.result:type_name -> google.protobuf.Any
	16, // 16: Ydb.Operations.Operation.metadata:type_name -> google.protobuf.Any
	17, // 17: Ydb.Operations.Operation.cost_info:type_name -> Ydb.CostInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_protos_ydb_operation_proto_init() }
func file_protos_ydb_operation_proto_init() {
	if File_protos_ydb_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_operation_proto_rawDesc), len(file_protos_ydb_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_operation_proto_goTypes,
		DependencyIndexes: file_protos_ydb_operation_proto_depIdxs,
		EnumInfos:         file_protos_ydb_operation_proto_enumTypes,
		MessageInfos:      file_protos_ydb_operation_proto_msgTypes,
	}.Build()
	File_protos_ydb_operation_proto = out.File
	file_protos_ydb_operation_proto_goTypes = nil
	file_protos_ydb_operation_proto_depIdxs = nil
}
