// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: draft/protos/ydb_maintenance.proto

package Ydb_Maintenance

import (
	Ydb "github.com/ydb-platform/ydb-go-genproto/protos/Ydb"
	Ydb_Discovery "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Discovery"
	Ydb_Operations "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Operations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents state of an abstract item: e.g. node or device.
type ItemState int32

const (
	// Item's state couldn't be identified.
	ItemState_ITEM_STATE_UNSPECIFIED ItemState = 0
	// Item is up.
	ItemState_ITEM_STATE_UP ItemState = 1
	// Item is down due to planned maintenance.
	ItemState_ITEM_STATE_MAINTENANCE ItemState = 2
	// Item is down off-schedule.
	ItemState_ITEM_STATE_DOWN ItemState = 3
)

// Enum value maps for ItemState.
var (
	ItemState_name = map[int32]string{
		0: "ITEM_STATE_UNSPECIFIED",
		1: "ITEM_STATE_UP",
		2: "ITEM_STATE_MAINTENANCE",
		3: "ITEM_STATE_DOWN",
	}
	ItemState_value = map[string]int32{
		"ITEM_STATE_UNSPECIFIED": 0,
		"ITEM_STATE_UP":          1,
		"ITEM_STATE_MAINTENANCE": 2,
		"ITEM_STATE_DOWN":        3,
	}
)

func (x ItemState) Enum() *ItemState {
	p := new(ItemState)
	*p = x
	return p
}

func (x ItemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemState) Descriptor() protoreflect.EnumDescriptor {
	return file_draft_protos_ydb_maintenance_proto_enumTypes[0].Descriptor()
}

func (ItemState) Type() protoreflect.EnumType {
	return &file_draft_protos_ydb_maintenance_proto_enumTypes[0]
}

func (x ItemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type AvailabilityMode int32

const (
	AvailabilityMode_AVAILABILITY_MODE_UNSPECIFIED AvailabilityMode = 0
	// In this mode allowed:
	// - at most 1 unavailable disk in each affected storage group;
	// - at most 1 unavailable state storage ring.
	// For nodes tenant and cluster policies are followed.
	AvailabilityMode_AVAILABILITY_MODE_STRONG AvailabilityMode = 1
	// In this mode:
	//   - total number of an unavailable disks in each affected storage group
	//     shouldn't exceed number of parity parts in that group;
	//   - it is allowed to disable (n_to_select - 1) / 2 state storage rings.
	//
	// Nodes are handled as in strong mode.
	AvailabilityMode_AVAILABILITY_MODE_WEAK AvailabilityMode = 2
	// Ignore any storage group & state storage checks.
	// Using this mode might cause data unavailability.
	AvailabilityMode_AVAILABILITY_MODE_FORCE AvailabilityMode = 3
)

// Enum value maps for AvailabilityMode.
var (
	AvailabilityMode_name = map[int32]string{
		0: "AVAILABILITY_MODE_UNSPECIFIED",
		1: "AVAILABILITY_MODE_STRONG",
		2: "AVAILABILITY_MODE_WEAK",
		3: "AVAILABILITY_MODE_FORCE",
	}
	AvailabilityMode_value = map[string]int32{
		"AVAILABILITY_MODE_UNSPECIFIED": 0,
		"AVAILABILITY_MODE_STRONG":      1,
		"AVAILABILITY_MODE_WEAK":        2,
		"AVAILABILITY_MODE_FORCE":       3,
	}
)

func (x AvailabilityMode) Enum() *AvailabilityMode {
	p := new(AvailabilityMode)
	*p = x
	return p
}

func (x AvailabilityMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityMode) Descriptor() protoreflect.EnumDescriptor {
	return file_draft_protos_ydb_maintenance_proto_enumTypes[1].Descriptor()
}

func (AvailabilityMode) Type() protoreflect.EnumType {
	return &file_draft_protos_ydb_maintenance_proto_enumTypes[1]
}

func (x AvailabilityMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ActionState_ActionStatus int32

const (
	ActionState_ACTION_STATUS_UNSPECIFIED ActionState_ActionStatus = 0
	// Action can't be performed now.
	ActionState_ACTION_STATUS_PENDING ActionState_ActionStatus = 1
	// Action performed: e.g. lock is taken.
	ActionState_ACTION_STATUS_PERFORMED ActionState_ActionStatus = 2
)

// Enum value maps for ActionState_ActionStatus.
var (
	ActionState_ActionStatus_name = map[int32]string{
		0: "ACTION_STATUS_UNSPECIFIED",
		1: "ACTION_STATUS_PENDING",
		2: "ACTION_STATUS_PERFORMED",
	}
	ActionState_ActionStatus_value = map[string]int32{
		"ACTION_STATUS_UNSPECIFIED": 0,
		"ACTION_STATUS_PENDING":     1,
		"ACTION_STATUS_PERFORMED":   2,
	}
)

func (x ActionState_ActionStatus) Enum() *ActionState_ActionStatus {
	p := new(ActionState_ActionStatus)
	*p = x
	return p
}

func (x ActionState_ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionState_ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_draft_protos_ydb_maintenance_proto_enumTypes[2].Descriptor()
}

func (ActionState_ActionStatus) Type() protoreflect.EnumType {
	return &file_draft_protos_ydb_maintenance_proto_enumTypes[2]
}

func (x ActionState_ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ActionState_ActionReason int32

const (
	ActionState_ACTION_REASON_UNSPECIFIED ActionState_ActionReason = 0
	// Everything is ok.
	ActionState_ACTION_REASON_OK ActionState_ActionReason = 1
	// Affected storage group has too many unavailable (locked or down) vdisks.
	ActionState_ACTION_REASON_TOO_MANY_UNAVAILABLE_VDISKS ActionState_ActionReason = 2
	// Too many unavailable state storage rings.
	ActionState_ACTION_REASON_TOO_MANY_UNAVAILABLE_STATE_STORAGE_RINGS ActionState_ActionReason = 3
	// Too many disabled nodes (storage & dynamic) in cluster.
	ActionState_ACTION_REASON_DISABLED_NODES_LIMIT_REACHED ActionState_ActionReason = 4
	// Too many disabled dynamic nodes of specific tenant.
	ActionState_ACTION_REASON_TENANT_DISABLED_NODES_LIMIT_REACHED ActionState_ActionReason = 5
	// Wrong request.
	ActionState_ACTION_REASON_WRONG_REQUEST ActionState_ActionReason = 6
	// Too many unavailable nodes with system tablets.
	ActionState_ACTION_REASON_SYS_TABLETS_NODE_LIMIT_REACHED ActionState_ActionReason = 7
	// Generic reason.
	ActionState_ACTION_REASON_GENERIC ActionState_ActionReason = 8
)

// Enum value maps for ActionState_ActionReason.
var (
	ActionState_ActionReason_name = map[int32]string{
		0: "ACTION_REASON_UNSPECIFIED",
		1: "ACTION_REASON_OK",
		2: "ACTION_REASON_TOO_MANY_UNAVAILABLE_VDISKS",
		3: "ACTION_REASON_TOO_MANY_UNAVAILABLE_STATE_STORAGE_RINGS",
		4: "ACTION_REASON_DISABLED_NODES_LIMIT_REACHED",
		5: "ACTION_REASON_TENANT_DISABLED_NODES_LIMIT_REACHED",
		6: "ACTION_REASON_WRONG_REQUEST",
		7: "ACTION_REASON_SYS_TABLETS_NODE_LIMIT_REACHED",
		8: "ACTION_REASON_GENERIC",
	}
	ActionState_ActionReason_value = map[string]int32{
		"ACTION_REASON_UNSPECIFIED":                              0,
		"ACTION_REASON_OK":                                       1,
		"ACTION_REASON_TOO_MANY_UNAVAILABLE_VDISKS":              2,
		"ACTION_REASON_TOO_MANY_UNAVAILABLE_STATE_STORAGE_RINGS": 3,
		"ACTION_REASON_DISABLED_NODES_LIMIT_REACHED":             4,
		"ACTION_REASON_TENANT_DISABLED_NODES_LIMIT_REACHED":      5,
		"ACTION_REASON_WRONG_REQUEST":                            6,
		"ACTION_REASON_SYS_TABLETS_NODE_LIMIT_REACHED":           7,
		"ACTION_REASON_GENERIC":                                  8,
	}
)

func (x ActionState_ActionReason) Enum() *ActionState_ActionReason {
	p := new(ActionState_ActionReason)
	*p = x
	return p
}

func (x ActionState_ActionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionState_ActionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_draft_protos_ydb_maintenance_proto_enumTypes[3].Descriptor()
}

func (ActionState_ActionReason) Type() protoreflect.EnumType {
	return &file_draft_protos_ydb_maintenance_proto_enumTypes[3]
}

func (x ActionState_ActionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Node struct {
	state                protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_NodeId    uint32                      `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3"`
	xxx_hidden_Host      string                      `protobuf:"bytes,2,opt,name=host,proto3"`
	xxx_hidden_Port      uint32                      `protobuf:"varint,3,opt,name=port,proto3"`
	xxx_hidden_Location  *Ydb_Discovery.NodeLocation `protobuf:"bytes,4,opt,name=location,proto3"`
	xxx_hidden_State     ItemState                   `protobuf:"varint,5,opt,name=state,proto3,enum=Ydb.Maintenance.ItemState"`
	xxx_hidden_Type      isNode_Type                 `protobuf_oneof:"type"`
	xxx_hidden_StartTime *timestamppb.Timestamp      `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3"`
	xxx_hidden_Version   string                      `protobuf:"bytes,9,opt,name=version,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetNodeId() uint32 {
	if x != nil {
		return x.xxx_hidden_NodeId
	}
	return 0
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *Node) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *Node) GetLocation() *Ydb_Discovery.NodeLocation {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return nil
}

func (x *Node) GetState() ItemState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ItemState_ITEM_STATE_UNSPECIFIED
}

func (x *Node) GetStorage() *Node_StorageNode {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*node_Storage); ok {
			return x.Storage
		}
	}
	return nil
}

func (x *Node) GetDynamic() *Node_DynamicNode {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*node_Dynamic); ok {
			return x.Dynamic
		}
	}
	return nil
}

func (x *Node) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *Node) SetNodeId(v uint32) {
	x.xxx_hidden_NodeId = v
}

func (x *Node) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *Node) SetPort(v uint32) {
	x.xxx_hidden_Port = v
}

func (x *Node) SetLocation(v *Ydb_Discovery.NodeLocation) {
	x.xxx_hidden_Location = v
}

func (x *Node) SetState(v ItemState) {
	x.xxx_hidden_State = v
}

func (x *Node) SetStorage(v *Node_StorageNode) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &node_Storage{v}
}

func (x *Node) SetDynamic(v *Node_DynamicNode) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &node_Dynamic{v}
}

func (x *Node) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *Node) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *Node) HasLocation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Location != nil
}

func (x *Node) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *Node) HasStorage() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*node_Storage)
	return ok
}

func (x *Node) HasDynamic() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*node_Dynamic)
	return ok
}

func (x *Node) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *Node) ClearLocation() {
	x.xxx_hidden_Location = nil
}

func (x *Node) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *Node) ClearStorage() {
	if _, ok := x.xxx_hidden_Type.(*node_Storage); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Node) ClearDynamic() {
	if _, ok := x.xxx_hidden_Type.(*node_Dynamic); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Node) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

const Node_Type_not_set_case case_Node_Type = 0
const Node_Storage_case case_Node_Type = 6
const Node_Dynamic_case case_Node_Type = 7

func (x *Node) WhichType() case_Node_Type {
	if x == nil {
		return Node_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *node_Storage:
		return Node_Storage_case
	case *node_Dynamic:
		return Node_Dynamic_case
	default:
		return Node_Type_not_set_case
	}
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NodeId   uint32
	Host     string
	Port     uint32
	Location *Ydb_Discovery.NodeLocation
	State    ItemState
	// Fields of oneof xxx_hidden_Type:
	Storage *Node_StorageNode
	Dynamic *Node_DynamicNode
	// -- end of xxx_hidden_Type
	// start_time defines time when node was registered in cms.
	StartTime *timestamppb.Timestamp
	// version defines YDB version for current Node.
	// For example, 'ydb-stable-24-1'.
	Version string
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NodeId = b.NodeId
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_State = b.State
	if b.Storage != nil {
		x.xxx_hidden_Type = &node_Storage{b.Storage}
	}
	if b.Dynamic != nil {
		x.xxx_hidden_Type = &node_Dynamic{b.Dynamic}
	}
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_Version = b.Version
	return m0
}

type case_Node_Type protoreflect.FieldNumber

func (x case_Node_Type) String() string {
	md := file_draft_protos_ydb_maintenance_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isNode_Type interface {
	isNode_Type()
}

type node_Storage struct {
	Storage *Node_StorageNode `protobuf:"bytes,6,opt,name=storage,proto3,oneof"`
}

type node_Dynamic struct {
	Dynamic *Node_DynamicNode `protobuf:"bytes,7,opt,name=dynamic,proto3,oneof"`
}

func (*node_Storage) isNode_Type() {}

func (*node_Dynamic) isNode_Type() {}

type ListClusterNodesRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ListClusterNodesRequest) Reset() {
	*x = ListClusterNodesRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClusterNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterNodesRequest) ProtoMessage() {}

func (x *ListClusterNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListClusterNodesRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *ListClusterNodesRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *ListClusterNodesRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *ListClusterNodesRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

type ListClusterNodesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
}

func (b0 ListClusterNodesRequest_builder) Build() *ListClusterNodesRequest {
	m0 := &ListClusterNodesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	return m0
}

type ListClusterNodesResult struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes *[]*Node               `protobuf:"bytes,1,rep,name=nodes,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListClusterNodesResult) Reset() {
	*x = ListClusterNodesResult{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClusterNodesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterNodesResult) ProtoMessage() {}

func (x *ListClusterNodesResult) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListClusterNodesResult) GetNodes() []*Node {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *ListClusterNodesResult) SetNodes(v []*Node) {
	x.xxx_hidden_Nodes = &v
}

type ListClusterNodesResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes []*Node
}

func (b0 ListClusterNodesResult_builder) Build() *ListClusterNodesResult {
	m0 := &ListClusterNodesResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	return m0
}

type ListClusterNodesResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListClusterNodesResponse) Reset() {
	*x = ListClusterNodesResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClusterNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterNodesResponse) ProtoMessage() {}

func (x *ListClusterNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListClusterNodesResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *ListClusterNodesResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *ListClusterNodesResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *ListClusterNodesResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type ListClusterNodesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation.result = ListClusterNodesResult
	Operation *Ydb_Operations.Operation
}

func (b0 ListClusterNodesResponse_builder) Build() *ListClusterNodesResponse {
	m0 := &ListClusterNodesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type MaintenanceTaskOptions struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskUid          string                 `protobuf:"bytes,1,opt,name=task_uid,json=taskUid,proto3"`
	xxx_hidden_Description      string                 `protobuf:"bytes,2,opt,name=description,proto3"`
	xxx_hidden_AvailabilityMode AvailabilityMode       `protobuf:"varint,3,opt,name=availability_mode,json=availabilityMode,proto3,enum=Ydb.Maintenance.AvailabilityMode"`
	xxx_hidden_DryRun           bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3"`
	xxx_hidden_Priority         int32                  `protobuf:"varint,5,opt,name=priority,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MaintenanceTaskOptions) Reset() {
	*x = MaintenanceTaskOptions{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceTaskOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceTaskOptions) ProtoMessage() {}

func (x *MaintenanceTaskOptions) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MaintenanceTaskOptions) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *MaintenanceTaskOptions) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *MaintenanceTaskOptions) GetAvailabilityMode() AvailabilityMode {
	if x != nil {
		return x.xxx_hidden_AvailabilityMode
	}
	return AvailabilityMode_AVAILABILITY_MODE_UNSPECIFIED
}

func (x *MaintenanceTaskOptions) GetDryRun() bool {
	if x != nil {
		return x.xxx_hidden_DryRun
	}
	return false
}

func (x *MaintenanceTaskOptions) GetPriority() int32 {
	if x != nil {
		return x.xxx_hidden_Priority
	}
	return 0
}

func (x *MaintenanceTaskOptions) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *MaintenanceTaskOptions) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *MaintenanceTaskOptions) SetAvailabilityMode(v AvailabilityMode) {
	x.xxx_hidden_AvailabilityMode = v
}

func (x *MaintenanceTaskOptions) SetDryRun(v bool) {
	x.xxx_hidden_DryRun = v
}

func (x *MaintenanceTaskOptions) SetPriority(v int32) {
	x.xxx_hidden_Priority = v
}

type MaintenanceTaskOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User-defined _unique_ task identifier.
	TaskUid string
	// User-defined description.
	Description string
	// Availability mode.
	AvailabilityMode AvailabilityMode
	DryRun           bool
	// Priority of the task. Lower value indicates higher priority.
	Priority int32
}

func (b0 MaintenanceTaskOptions_builder) Build() *MaintenanceTaskOptions {
	m0 := &MaintenanceTaskOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskUid = b.TaskUid
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_AvailabilityMode = b.AvailabilityMode
	x.xxx_hidden_DryRun = b.DryRun
	x.xxx_hidden_Priority = b.Priority
	return m0
}

// Used to describe the scope of a single action.
type ActionScope struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Scope isActionScope_Scope    `protobuf_oneof:"scope"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActionScope) Reset() {
	*x = ActionScope{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionScope) ProtoMessage() {}

func (x *ActionScope) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionScope) GetNodeId() uint32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Scope.(*actionScope_NodeId); ok {
			return x.NodeId
		}
	}
	return 0
}

func (x *ActionScope) GetHost() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Scope.(*actionScope_Host); ok {
			return x.Host
		}
	}
	return ""
}

func (x *ActionScope) SetNodeId(v uint32) {
	x.xxx_hidden_Scope = &actionScope_NodeId{v}
}

func (x *ActionScope) SetHost(v string) {
	x.xxx_hidden_Scope = &actionScope_Host{v}
}

func (x *ActionScope) HasScope() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scope != nil
}

func (x *ActionScope) HasNodeId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Scope.(*actionScope_NodeId)
	return ok
}

func (x *ActionScope) HasHost() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Scope.(*actionScope_Host)
	return ok
}

func (x *ActionScope) ClearScope() {
	x.xxx_hidden_Scope = nil
}

func (x *ActionScope) ClearNodeId() {
	if _, ok := x.xxx_hidden_Scope.(*actionScope_NodeId); ok {
		x.xxx_hidden_Scope = nil
	}
}

func (x *ActionScope) ClearHost() {
	if _, ok := x.xxx_hidden_Scope.(*actionScope_Host); ok {
		x.xxx_hidden_Scope = nil
	}
}

const ActionScope_Scope_not_set_case case_ActionScope_Scope = 0
const ActionScope_NodeId_case case_ActionScope_Scope = 1
const ActionScope_Host_case case_ActionScope_Scope = 2

func (x *ActionScope) WhichScope() case_ActionScope_Scope {
	if x == nil {
		return ActionScope_Scope_not_set_case
	}
	switch x.xxx_hidden_Scope.(type) {
	case *actionScope_NodeId:
		return ActionScope_NodeId_case
	case *actionScope_Host:
		return ActionScope_Host_case
	default:
		return ActionScope_Scope_not_set_case
	}
}

type ActionScope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Scope:
	NodeId *uint32
	Host   *string
	// -- end of xxx_hidden_Scope
}

func (b0 ActionScope_builder) Build() *ActionScope {
	m0 := &ActionScope{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NodeId != nil {
		x.xxx_hidden_Scope = &actionScope_NodeId{*b.NodeId}
	}
	if b.Host != nil {
		x.xxx_hidden_Scope = &actionScope_Host{*b.Host}
	}
	return m0
}

type case_ActionScope_Scope protoreflect.FieldNumber

func (x case_ActionScope_Scope) String() string {
	md := file_draft_protos_ydb_maintenance_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isActionScope_Scope interface {
	isActionScope_Scope()
}

type actionScope_NodeId struct {
	NodeId uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3,oneof"`
}

type actionScope_Host struct {
	Host string `protobuf:"bytes,2,opt,name=host,proto3,oneof"`
}

func (*actionScope_NodeId) isActionScope_Scope() {}

func (*actionScope_Host) isActionScope_Scope() {}

// Taking an exclusive lock to perform maintenance.
type LockAction struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Scope    *ActionScope           `protobuf:"bytes,1,opt,name=scope,proto3"`
	xxx_hidden_Duration *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LockAction) Reset() {
	*x = LockAction{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockAction) ProtoMessage() {}

func (x *LockAction) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LockAction) GetScope() *ActionScope {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return nil
}

func (x *LockAction) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Duration
	}
	return nil
}

func (x *LockAction) SetScope(v *ActionScope) {
	x.xxx_hidden_Scope = v
}

func (x *LockAction) SetDuration(v *durationpb.Duration) {
	x.xxx_hidden_Duration = v
}

func (x *LockAction) HasScope() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scope != nil
}

func (x *LockAction) HasDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Duration != nil
}

func (x *LockAction) ClearScope() {
	x.xxx_hidden_Scope = nil
}

func (x *LockAction) ClearDuration() {
	x.xxx_hidden_Duration = nil
}

type LockAction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Scope    *ActionScope
	Duration *durationpb.Duration
}

func (b0 LockAction_builder) Build() *LockAction {
	m0 := &LockAction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Scope = b.Scope
	x.xxx_hidden_Duration = b.Duration
	return m0
}

type Action struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Action isAction_Action        `protobuf_oneof:"action"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Action) GetLockAction() *LockAction {
	if x != nil {
		if x, ok := x.xxx_hidden_Action.(*action_LockAction); ok {
			return x.LockAction
		}
	}
	return nil
}

func (x *Action) SetLockAction(v *LockAction) {
	if v == nil {
		x.xxx_hidden_Action = nil
		return
	}
	x.xxx_hidden_Action = &action_LockAction{v}
}

func (x *Action) HasAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Action != nil
}

func (x *Action) HasLockAction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Action.(*action_LockAction)
	return ok
}

func (x *Action) ClearAction() {
	x.xxx_hidden_Action = nil
}

func (x *Action) ClearLockAction() {
	if _, ok := x.xxx_hidden_Action.(*action_LockAction); ok {
		x.xxx_hidden_Action = nil
	}
}

const Action_Action_not_set_case case_Action_Action = 0
const Action_LockAction_case case_Action_Action = 1

func (x *Action) WhichAction() case_Action_Action {
	if x == nil {
		return Action_Action_not_set_case
	}
	switch x.xxx_hidden_Action.(type) {
	case *action_LockAction:
		return Action_LockAction_case
	default:
		return Action_Action_not_set_case
	}
}

type Action_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Action:
	LockAction *LockAction
	// -- end of xxx_hidden_Action
}

func (b0 Action_builder) Build() *Action {
	m0 := &Action{}
	b, x := &b0, m0
	_, _ = b, x
	if b.LockAction != nil {
		x.xxx_hidden_Action = &action_LockAction{b.LockAction}
	}
	return m0
}

type case_Action_Action protoreflect.FieldNumber

func (x case_Action_Action) String() string {
	md := file_draft_protos_ydb_maintenance_proto_msgTypes[7].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAction_Action interface {
	isAction_Action()
}

type action_LockAction struct {
	LockAction *LockAction `protobuf:"bytes,1,opt,name=lock_action,json=lockAction,proto3,oneof"`
}

func (*action_LockAction) isAction_Action() {}

type ActionGroup struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Actions *[]*Action             `protobuf:"bytes,1,rep,name=actions,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActionGroup) Reset() {
	*x = ActionGroup{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionGroup) ProtoMessage() {}

func (x *ActionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionGroup) GetActions() []*Action {
	if x != nil {
		if x.xxx_hidden_Actions != nil {
			return *x.xxx_hidden_Actions
		}
	}
	return nil
}

func (x *ActionGroup) SetActions(v []*Action) {
	x.xxx_hidden_Actions = &v
}

type ActionGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Actions []*Action
}

func (b0 ActionGroup_builder) Build() *ActionGroup {
	m0 := &ActionGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Actions = &b.Actions
	return m0
}

type CreateMaintenanceTaskRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_TaskOptions     *MaintenanceTaskOptions         `protobuf:"bytes,2,opt,name=task_options,json=taskOptions,proto3"`
	xxx_hidden_ActionGroups    *[]*ActionGroup                 `protobuf:"bytes,3,rep,name=action_groups,json=actionGroups,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateMaintenanceTaskRequest) Reset() {
	*x = CreateMaintenanceTaskRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaintenanceTaskRequest) ProtoMessage() {}

func (x *CreateMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateMaintenanceTaskRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *CreateMaintenanceTaskRequest) GetTaskOptions() *MaintenanceTaskOptions {
	if x != nil {
		return x.xxx_hidden_TaskOptions
	}
	return nil
}

func (x *CreateMaintenanceTaskRequest) GetActionGroups() []*ActionGroup {
	if x != nil {
		if x.xxx_hidden_ActionGroups != nil {
			return *x.xxx_hidden_ActionGroups
		}
	}
	return nil
}

func (x *CreateMaintenanceTaskRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *CreateMaintenanceTaskRequest) SetTaskOptions(v *MaintenanceTaskOptions) {
	x.xxx_hidden_TaskOptions = v
}

func (x *CreateMaintenanceTaskRequest) SetActionGroups(v []*ActionGroup) {
	x.xxx_hidden_ActionGroups = &v
}

func (x *CreateMaintenanceTaskRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *CreateMaintenanceTaskRequest) HasTaskOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TaskOptions != nil
}

func (x *CreateMaintenanceTaskRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

func (x *CreateMaintenanceTaskRequest) ClearTaskOptions() {
	x.xxx_hidden_TaskOptions = nil
}

type CreateMaintenanceTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	TaskOptions     *MaintenanceTaskOptions
	ActionGroups    []*ActionGroup
}

func (b0 CreateMaintenanceTaskRequest_builder) Build() *CreateMaintenanceTaskRequest {
	m0 := &CreateMaintenanceTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	x.xxx_hidden_TaskOptions = b.TaskOptions
	x.xxx_hidden_ActionGroups = &b.ActionGroups
	return m0
}

type RefreshMaintenanceTaskRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_TaskUid         string                          `protobuf:"bytes,2,opt,name=task_uid,json=taskUid,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RefreshMaintenanceTaskRequest) Reset() {
	*x = RefreshMaintenanceTaskRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshMaintenanceTaskRequest) ProtoMessage() {}

func (x *RefreshMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RefreshMaintenanceTaskRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *RefreshMaintenanceTaskRequest) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *RefreshMaintenanceTaskRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *RefreshMaintenanceTaskRequest) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *RefreshMaintenanceTaskRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *RefreshMaintenanceTaskRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

type RefreshMaintenanceTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	TaskUid         string
}

func (b0 RefreshMaintenanceTaskRequest_builder) Build() *RefreshMaintenanceTaskRequest {
	m0 := &RefreshMaintenanceTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	x.xxx_hidden_TaskUid = b.TaskUid
	return m0
}

type ActionUid struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskUid  string                 `protobuf:"bytes,1,opt,name=task_uid,json=taskUid,proto3"`
	xxx_hidden_GroupId  string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3"`
	xxx_hidden_ActionId string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActionUid) Reset() {
	*x = ActionUid{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionUid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionUid) ProtoMessage() {}

func (x *ActionUid) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionUid) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *ActionUid) GetGroupId() string {
	if x != nil {
		return x.xxx_hidden_GroupId
	}
	return ""
}

func (x *ActionUid) GetActionId() string {
	if x != nil {
		return x.xxx_hidden_ActionId
	}
	return ""
}

func (x *ActionUid) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *ActionUid) SetGroupId(v string) {
	x.xxx_hidden_GroupId = v
}

func (x *ActionUid) SetActionId(v string) {
	x.xxx_hidden_ActionId = v
}

type ActionUid_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskUid string
	// Unique ids within a single task, assigned by the server.
	GroupId  string
	ActionId string
}

func (b0 ActionUid_builder) Build() *ActionUid {
	m0 := &ActionUid{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskUid = b.TaskUid
	x.xxx_hidden_GroupId = b.GroupId
	x.xxx_hidden_ActionId = b.ActionId
	return m0
}

type ActionState struct {
	state                    protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Action        *Action                  `protobuf:"bytes,1,opt,name=action,proto3"`
	xxx_hidden_ActionUid     *ActionUid               `protobuf:"bytes,2,opt,name=action_uid,json=actionUid,proto3"`
	xxx_hidden_Status        ActionState_ActionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=Ydb.Maintenance.ActionState_ActionStatus"`
	xxx_hidden_Reason        ActionState_ActionReason `protobuf:"varint,4,opt,name=reason,proto3,enum=Ydb.Maintenance.ActionState_ActionReason"`
	xxx_hidden_ReasonDetails string                   `protobuf:"bytes,6,opt,name=reason_details,json=reasonDetails,proto3"`
	xxx_hidden_Deadline      *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=deadline,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActionState) Reset() {
	*x = ActionState{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionState) ProtoMessage() {}

func (x *ActionState) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionState) GetAction() *Action {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return nil
}

func (x *ActionState) GetActionUid() *ActionUid {
	if x != nil {
		return x.xxx_hidden_ActionUid
	}
	return nil
}

func (x *ActionState) GetStatus() ActionState_ActionStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ActionState_ACTION_STATUS_UNSPECIFIED
}

func (x *ActionState) GetReason() ActionState_ActionReason {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ActionState_ACTION_REASON_UNSPECIFIED
}

func (x *ActionState) GetReasonDetails() string {
	if x != nil {
		return x.xxx_hidden_ReasonDetails
	}
	return ""
}

func (x *ActionState) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Deadline
	}
	return nil
}

func (x *ActionState) SetAction(v *Action) {
	x.xxx_hidden_Action = v
}

func (x *ActionState) SetActionUid(v *ActionUid) {
	x.xxx_hidden_ActionUid = v
}

func (x *ActionState) SetStatus(v ActionState_ActionStatus) {
	x.xxx_hidden_Status = v
}

func (x *ActionState) SetReason(v ActionState_ActionReason) {
	x.xxx_hidden_Reason = v
}

func (x *ActionState) SetReasonDetails(v string) {
	x.xxx_hidden_ReasonDetails = v
}

func (x *ActionState) SetDeadline(v *timestamppb.Timestamp) {
	x.xxx_hidden_Deadline = v
}

func (x *ActionState) HasAction() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Action != nil
}

func (x *ActionState) HasActionUid() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ActionUid != nil
}

func (x *ActionState) HasDeadline() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deadline != nil
}

func (x *ActionState) ClearAction() {
	x.xxx_hidden_Action = nil
}

func (x *ActionState) ClearActionUid() {
	x.xxx_hidden_ActionUid = nil
}

func (x *ActionState) ClearDeadline() {
	x.xxx_hidden_Deadline = nil
}

type ActionState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Action        *Action
	ActionUid     *ActionUid
	Status        ActionState_ActionStatus
	Reason        ActionState_ActionReason
	ReasonDetails string
	Deadline      *timestamppb.Timestamp
}

func (b0 ActionState_builder) Build() *ActionState {
	m0 := &ActionState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_ActionUid = b.ActionUid
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Reason = b.Reason
	x.xxx_hidden_ReasonDetails = b.ReasonDetails
	x.xxx_hidden_Deadline = b.Deadline
	return m0
}

type ActionGroupStates struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ActionStates *[]*ActionState        `protobuf:"bytes,1,rep,name=action_states,json=actionStates,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActionGroupStates) Reset() {
	*x = ActionGroupStates{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionGroupStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionGroupStates) ProtoMessage() {}

func (x *ActionGroupStates) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActionGroupStates) GetActionStates() []*ActionState {
	if x != nil {
		if x.xxx_hidden_ActionStates != nil {
			return *x.xxx_hidden_ActionStates
		}
	}
	return nil
}

func (x *ActionGroupStates) SetActionStates(v []*ActionState) {
	x.xxx_hidden_ActionStates = &v
}

type ActionGroupStates_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActionStates []*ActionState
}

func (b0 ActionGroupStates_builder) Build() *ActionGroupStates {
	m0 := &ActionGroupStates{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ActionStates = &b.ActionStates
	return m0
}

type MaintenanceTaskResult struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskUid           string                 `protobuf:"bytes,1,opt,name=task_uid,json=taskUid,proto3"`
	xxx_hidden_ActionGroupStates *[]*ActionGroupStates  `protobuf:"bytes,2,rep,name=action_group_states,json=actionGroupStates,proto3"`
	xxx_hidden_RetryAfter        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=retry_after,json=retryAfter,proto3,oneof"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *MaintenanceTaskResult) Reset() {
	*x = MaintenanceTaskResult{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceTaskResult) ProtoMessage() {}

func (x *MaintenanceTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MaintenanceTaskResult) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *MaintenanceTaskResult) GetActionGroupStates() []*ActionGroupStates {
	if x != nil {
		if x.xxx_hidden_ActionGroupStates != nil {
			return *x.xxx_hidden_ActionGroupStates
		}
	}
	return nil
}

func (x *MaintenanceTaskResult) GetRetryAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RetryAfter
	}
	return nil
}

func (x *MaintenanceTaskResult) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *MaintenanceTaskResult) SetActionGroupStates(v []*ActionGroupStates) {
	x.xxx_hidden_ActionGroupStates = &v
}

func (x *MaintenanceTaskResult) SetRetryAfter(v *timestamppb.Timestamp) {
	x.xxx_hidden_RetryAfter = v
}

func (x *MaintenanceTaskResult) HasRetryAfter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RetryAfter != nil
}

func (x *MaintenanceTaskResult) ClearRetryAfter() {
	x.xxx_hidden_RetryAfter = nil
}

type MaintenanceTaskResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskUid           string
	ActionGroupStates []*ActionGroupStates
	// Try again after this deadline. Specified if there are no performed actions.
	RetryAfter *timestamppb.Timestamp
}

func (b0 MaintenanceTaskResult_builder) Build() *MaintenanceTaskResult {
	m0 := &MaintenanceTaskResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskUid = b.TaskUid
	x.xxx_hidden_ActionGroupStates = &b.ActionGroupStates
	x.xxx_hidden_RetryAfter = b.RetryAfter
	return m0
}

type MaintenanceTaskResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MaintenanceTaskResponse) Reset() {
	*x = MaintenanceTaskResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceTaskResponse) ProtoMessage() {}

func (x *MaintenanceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MaintenanceTaskResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *MaintenanceTaskResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *MaintenanceTaskResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *MaintenanceTaskResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type MaintenanceTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation.result = MaintenanceTaskResult
	Operation *Ydb_Operations.Operation
}

func (b0 MaintenanceTaskResponse_builder) Build() *MaintenanceTaskResponse {
	m0 := &MaintenanceTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type GetMaintenanceTaskRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_TaskUid         string                          `protobuf:"bytes,2,opt,name=task_uid,json=taskUid,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetMaintenanceTaskRequest) Reset() {
	*x = GetMaintenanceTaskRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceTaskRequest) ProtoMessage() {}

func (x *GetMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMaintenanceTaskRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *GetMaintenanceTaskRequest) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *GetMaintenanceTaskRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *GetMaintenanceTaskRequest) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *GetMaintenanceTaskRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *GetMaintenanceTaskRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

type GetMaintenanceTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	TaskUid         string
}

func (b0 GetMaintenanceTaskRequest_builder) Build() *GetMaintenanceTaskRequest {
	m0 := &GetMaintenanceTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	x.xxx_hidden_TaskUid = b.TaskUid
	return m0
}

type GetMaintenanceTaskResult struct {
	state                        protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_TaskOptions       *MaintenanceTaskOptions `protobuf:"bytes,1,opt,name=task_options,json=taskOptions,proto3"`
	xxx_hidden_ActionGroupStates *[]*ActionGroupStates   `protobuf:"bytes,2,rep,name=action_group_states,json=actionGroupStates,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GetMaintenanceTaskResult) Reset() {
	*x = GetMaintenanceTaskResult{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceTaskResult) ProtoMessage() {}

func (x *GetMaintenanceTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMaintenanceTaskResult) GetTaskOptions() *MaintenanceTaskOptions {
	if x != nil {
		return x.xxx_hidden_TaskOptions
	}
	return nil
}

func (x *GetMaintenanceTaskResult) GetActionGroupStates() []*ActionGroupStates {
	if x != nil {
		if x.xxx_hidden_ActionGroupStates != nil {
			return *x.xxx_hidden_ActionGroupStates
		}
	}
	return nil
}

func (x *GetMaintenanceTaskResult) SetTaskOptions(v *MaintenanceTaskOptions) {
	x.xxx_hidden_TaskOptions = v
}

func (x *GetMaintenanceTaskResult) SetActionGroupStates(v []*ActionGroupStates) {
	x.xxx_hidden_ActionGroupStates = &v
}

func (x *GetMaintenanceTaskResult) HasTaskOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TaskOptions != nil
}

func (x *GetMaintenanceTaskResult) ClearTaskOptions() {
	x.xxx_hidden_TaskOptions = nil
}

type GetMaintenanceTaskResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskOptions       *MaintenanceTaskOptions
	ActionGroupStates []*ActionGroupStates
}

func (b0 GetMaintenanceTaskResult_builder) Build() *GetMaintenanceTaskResult {
	m0 := &GetMaintenanceTaskResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TaskOptions = b.TaskOptions
	x.xxx_hidden_ActionGroupStates = &b.ActionGroupStates
	return m0
}

type GetMaintenanceTaskResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMaintenanceTaskResponse) Reset() {
	*x = GetMaintenanceTaskResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMaintenanceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaintenanceTaskResponse) ProtoMessage() {}

func (x *GetMaintenanceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetMaintenanceTaskResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *GetMaintenanceTaskResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *GetMaintenanceTaskResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *GetMaintenanceTaskResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type GetMaintenanceTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation.result = GetMaintenanceTaskResult
	Operation *Ydb_Operations.Operation
}

func (b0 GetMaintenanceTaskResponse_builder) Build() *GetMaintenanceTaskResponse {
	m0 := &GetMaintenanceTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type ListMaintenanceTasksRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_User            *string                         `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ListMaintenanceTasksRequest) Reset() {
	*x = ListMaintenanceTasksRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceTasksRequest) ProtoMessage() {}

func (x *ListMaintenanceTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMaintenanceTasksRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *ListMaintenanceTasksRequest) GetUser() string {
	if x != nil {
		if x.xxx_hidden_User != nil {
			return *x.xxx_hidden_User
		}
		return ""
	}
	return ""
}

func (x *ListMaintenanceTasksRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *ListMaintenanceTasksRequest) SetUser(v string) {
	x.xxx_hidden_User = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ListMaintenanceTasksRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *ListMaintenanceTasksRequest) HasUser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListMaintenanceTasksRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

func (x *ListMaintenanceTasksRequest) ClearUser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_User = nil
}

type ListMaintenanceTasksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// User SID (Security ID).
	// If specified, it will return the tasks created by this user.
	// Otherwise all tasks will be returned.
	User *string
}

func (b0 ListMaintenanceTasksRequest_builder) Build() *ListMaintenanceTasksRequest {
	m0 := &ListMaintenanceTasksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	if b.User != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_User = b.User
	}
	return m0
}

type ListMaintenanceTasksResult struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TasksUids []string               `protobuf:"bytes,1,rep,name=tasks_uids,json=tasksUids,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListMaintenanceTasksResult) Reset() {
	*x = ListMaintenanceTasksResult{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceTasksResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceTasksResult) ProtoMessage() {}

func (x *ListMaintenanceTasksResult) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMaintenanceTasksResult) GetTasksUids() []string {
	if x != nil {
		return x.xxx_hidden_TasksUids
	}
	return nil
}

func (x *ListMaintenanceTasksResult) SetTasksUids(v []string) {
	x.xxx_hidden_TasksUids = v
}

type ListMaintenanceTasksResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TasksUids []string
}

func (b0 ListMaintenanceTasksResult_builder) Build() *ListMaintenanceTasksResult {
	m0 := &ListMaintenanceTasksResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TasksUids = b.TasksUids
	return m0
}

type ListMaintenanceTasksResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListMaintenanceTasksResponse) Reset() {
	*x = ListMaintenanceTasksResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaintenanceTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaintenanceTasksResponse) ProtoMessage() {}

func (x *ListMaintenanceTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMaintenanceTasksResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *ListMaintenanceTasksResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *ListMaintenanceTasksResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *ListMaintenanceTasksResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type ListMaintenanceTasksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation.result = ListMaintenanceTasksResult
	Operation *Ydb_Operations.Operation
}

func (b0 ListMaintenanceTasksResponse_builder) Build() *ListMaintenanceTasksResponse {
	m0 := &ListMaintenanceTasksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type DropMaintenanceTaskRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_TaskUid         string                          `protobuf:"bytes,2,opt,name=task_uid,json=taskUid,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DropMaintenanceTaskRequest) Reset() {
	*x = DropMaintenanceTaskRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropMaintenanceTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropMaintenanceTaskRequest) ProtoMessage() {}

func (x *DropMaintenanceTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DropMaintenanceTaskRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *DropMaintenanceTaskRequest) GetTaskUid() string {
	if x != nil {
		return x.xxx_hidden_TaskUid
	}
	return ""
}

func (x *DropMaintenanceTaskRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *DropMaintenanceTaskRequest) SetTaskUid(v string) {
	x.xxx_hidden_TaskUid = v
}

func (x *DropMaintenanceTaskRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *DropMaintenanceTaskRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

type DropMaintenanceTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	TaskUid         string
}

func (b0 DropMaintenanceTaskRequest_builder) Build() *DropMaintenanceTaskRequest {
	m0 := &DropMaintenanceTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	x.xxx_hidden_TaskUid = b.TaskUid
	return m0
}

type ManageMaintenanceTaskResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ManageMaintenanceTaskResponse) Reset() {
	*x = ManageMaintenanceTaskResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageMaintenanceTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageMaintenanceTaskResponse) ProtoMessage() {}

func (x *ManageMaintenanceTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ManageMaintenanceTaskResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *ManageMaintenanceTaskResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *ManageMaintenanceTaskResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *ManageMaintenanceTaskResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type ManageMaintenanceTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Operation *Ydb_Operations.Operation
}

func (b0 ManageMaintenanceTaskResponse_builder) Build() *ManageMaintenanceTaskResponse {
	m0 := &ManageMaintenanceTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type CompleteActionRequest struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3"`
	xxx_hidden_ActionUids      *[]*ActionUid                   `protobuf:"bytes,2,rep,name=action_uids,json=actionUids,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CompleteActionRequest) Reset() {
	*x = CompleteActionRequest{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActionRequest) ProtoMessage() {}

func (x *CompleteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompleteActionRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.xxx_hidden_OperationParams
	}
	return nil
}

func (x *CompleteActionRequest) GetActionUids() []*ActionUid {
	if x != nil {
		if x.xxx_hidden_ActionUids != nil {
			return *x.xxx_hidden_ActionUids
		}
	}
	return nil
}

func (x *CompleteActionRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.xxx_hidden_OperationParams = v
}

func (x *CompleteActionRequest) SetActionUids(v []*ActionUid) {
	x.xxx_hidden_ActionUids = &v
}

func (x *CompleteActionRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OperationParams != nil
}

func (x *CompleteActionRequest) ClearOperationParams() {
	x.xxx_hidden_OperationParams = nil
}

type CompleteActionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	ActionUids      []*ActionUid
}

func (b0 CompleteActionRequest_builder) Build() *CompleteActionRequest {
	m0 := &CompleteActionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OperationParams = b.OperationParams
	x.xxx_hidden_ActionUids = &b.ActionUids
	return m0
}

type ManageActionResult struct {
	state                     protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_ActionStatuses *[]*ManageActionResult_Status `protobuf:"bytes,1,rep,name=action_statuses,json=actionStatuses,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ManageActionResult) Reset() {
	*x = ManageActionResult{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageActionResult) ProtoMessage() {}

func (x *ManageActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ManageActionResult) GetActionStatuses() []*ManageActionResult_Status {
	if x != nil {
		if x.xxx_hidden_ActionStatuses != nil {
			return *x.xxx_hidden_ActionStatuses
		}
	}
	return nil
}

func (x *ManageActionResult) SetActionStatuses(v []*ManageActionResult_Status) {
	x.xxx_hidden_ActionStatuses = &v
}

type ManageActionResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActionStatuses []*ManageActionResult_Status
}

func (b0 ManageActionResult_builder) Build() *ManageActionResult {
	m0 := &ManageActionResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ActionStatuses = &b.ActionStatuses
	return m0
}

type ManageActionResponse struct {
	state                protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Operation *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ManageActionResponse) Reset() {
	*x = ManageActionResponse{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageActionResponse) ProtoMessage() {}

func (x *ManageActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ManageActionResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return nil
}

func (x *ManageActionResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.xxx_hidden_Operation = v
}

func (x *ManageActionResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *ManageActionResponse) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

type ManageActionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation.result = ManageActionResult
	Operation *Ydb_Operations.Operation
}

func (b0 ManageActionResponse_builder) Build() *ManageActionResponse {
	m0 := &ManageActionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Operation = b.Operation
	return m0
}

type Node_StorageNode struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node_StorageNode) Reset() {
	*x = Node_StorageNode{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_StorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_StorageNode) ProtoMessage() {}

func (x *Node_StorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Node_StorageNode_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Node_StorageNode_builder) Build() *Node_StorageNode {
	m0 := &Node_StorageNode{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Node_DynamicNode struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tenant string                 `protobuf:"bytes,1,opt,name=tenant,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Node_DynamicNode) Reset() {
	*x = Node_DynamicNode{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_DynamicNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_DynamicNode) ProtoMessage() {}

func (x *Node_DynamicNode) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node_DynamicNode) GetTenant() string {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return ""
}

func (x *Node_DynamicNode) SetTenant(v string) {
	x.xxx_hidden_Tenant = v
}

type Node_DynamicNode_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tenant string
}

func (b0 Node_DynamicNode_builder) Build() *Node_DynamicNode {
	m0 := &Node_DynamicNode{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type ManageActionResult_Status struct {
	state                protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_ActionUid *ActionUid               `protobuf:"bytes,1,opt,name=action_uid,json=actionUid,proto3"`
	xxx_hidden_Status    Ydb.StatusIds_StatusCode `protobuf:"varint,2,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ManageActionResult_Status) Reset() {
	*x = ManageActionResult_Status{}
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageActionResult_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageActionResult_Status) ProtoMessage() {}

func (x *ManageActionResult_Status) ProtoReflect() protoreflect.Message {
	mi := &file_draft_protos_ydb_maintenance_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ManageActionResult_Status) GetActionUid() *ActionUid {
	if x != nil {
		return x.xxx_hidden_ActionUid
	}
	return nil
}

func (x *ManageActionResult_Status) GetStatus() Ydb.StatusIds_StatusCode {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return Ydb.StatusIds_StatusCode(0)
}

func (x *ManageActionResult_Status) SetActionUid(v *ActionUid) {
	x.xxx_hidden_ActionUid = v
}

func (x *ManageActionResult_Status) SetStatus(v Ydb.StatusIds_StatusCode) {
	x.xxx_hidden_Status = v
}

func (x *ManageActionResult_Status) HasActionUid() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ActionUid != nil
}

func (x *ManageActionResult_Status) ClearActionUid() {
	x.xxx_hidden_ActionUid = nil
}

type ManageActionResult_Status_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ActionUid *ActionUid
	Status    Ydb.StatusIds_StatusCode
}

func (b0 ManageActionResult_Status_builder) Build() *ManageActionResult_Status {
	m0 := &ManageActionResult_Status{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ActionUid = b.ActionUid
	x.xxx_hidden_Status = b.Status
	return m0
}

var File_draft_protos_ydb_maintenance_proto protoreflect.FileDescriptor

const file_draft_protos_ydb_maintenance_proto_rawDesc = "" +
	"\n" +
	"\"draft/protos/ydb_maintenance.proto\x12\x0fYdb.Maintenance\x1a#protos/annotations/validation.proto\x1a\x1dprotos/ydb_status_codes.proto\x1a\x1aprotos/ydb_discovery.proto\x1a\x1aprotos/ydb_operation.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x03\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x127\n" +
	"\blocation\x18\x04 \x01(\v2\x1b.Ydb.Discovery.NodeLocationR\blocation\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.Ydb.Maintenance.ItemStateR\x05state\x12=\n" +
	"\astorage\x18\x06 \x01(\v2!.Ydb.Maintenance.Node.StorageNodeH\x00R\astorage\x12=\n" +
	"\adynamic\x18\a \x01(\v2!.Ydb.Maintenance.Node.DynamicNodeH\x00R\adynamic\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x1a\r\n" +
	"\vStorageNode\x1a%\n" +
	"\vDynamicNode\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenantB\x06\n" +
	"\x04type\"e\n" +
	"\x17ListClusterNodesRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\"E\n" +
	"\x16ListClusterNodesResult\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.Ydb.Maintenance.NodeR\x05nodes\"S\n" +
	"\x18ListClusterNodesResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\xfd\x01\n" +
	"\x16MaintenanceTaskOptions\x12\"\n" +
	"\btask_uid\x18\x01 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\ataskUid\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\vdescription\x12N\n" +
	"\x11availability_mode\x18\x03 \x01(\x0e2!.Ydb.Maintenance.AvailabilityModeR\x10availabilityMode\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\x12+\n" +
	"\bpriority\x18\x05 \x01(\x05B\x0f\xb2\xe6*\v[-100; 100]R\bpriority\"P\n" +
	"\vActionScope\x12\x19\n" +
	"\anode_id\x18\x01 \x01(\rH\x00R\x06nodeId\x12\x1d\n" +
	"\x04host\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\xff\x01H\x00R\x04hostB\a\n" +
	"\x05scope\"w\n" +
	"\n" +
	"LockAction\x122\n" +
	"\x05scope\x18\x01 \x01(\v2\x1c.Ydb.Maintenance.ActionScopeR\x05scope\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\"R\n" +
	"\x06Action\x12>\n" +
	"\vlock_action\x18\x01 \x01(\v2\x1b.Ydb.Maintenance.LockActionH\x00R\n" +
	"lockActionB\b\n" +
	"\x06action\"H\n" +
	"\vActionGroup\x129\n" +
	"\aactions\x18\x01 \x03(\v2\x17.Ydb.Maintenance.ActionB\x06\x9a\xe6*\x02(\x01R\aactions\"\x81\x02\n" +
	"\x1cCreateMaintenanceTaskRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12J\n" +
	"\ftask_options\x18\x02 \x01(\v2'.Ydb.Maintenance.MaintenanceTaskOptionsR\vtaskOptions\x12I\n" +
	"\raction_groups\x18\x03 \x03(\v2\x1c.Ydb.Maintenance.ActionGroupB\x06\x9a\xe6*\x02(\x01R\factionGroups\"\x8f\x01\n" +
	"\x1dRefreshMaintenanceTaskRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12\"\n" +
	"\btask_uid\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\ataskUid\"y\n" +
	"\tActionUid\x12\"\n" +
	"\btask_uid\x18\x01 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\ataskUid\x12\"\n" +
	"\bgroup_id\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\agroupId\x12$\n" +
	"\taction_id\x18\x03 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\bactionId\"\xcb\x06\n" +
	"\vActionState\x12/\n" +
	"\x06action\x18\x01 \x01(\v2\x17.Ydb.Maintenance.ActionR\x06action\x129\n" +
	"\n" +
	"action_uid\x18\x02 \x01(\v2\x1a.Ydb.Maintenance.ActionUidR\tactionUid\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).Ydb.Maintenance.ActionState.ActionStatusR\x06status\x12A\n" +
	"\x06reason\x18\x04 \x01(\x0e2).Ydb.Maintenance.ActionState.ActionReasonR\x06reason\x12%\n" +
	"\x0ereason_details\x18\x06 \x01(\tR\rreasonDetails\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"e\n" +
	"\fActionStatus\x12\x1d\n" +
	"\x19ACTION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACTION_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17ACTION_STATUS_PERFORMED\x10\x02\"\x83\x03\n" +
	"\fActionReason\x12\x1d\n" +
	"\x19ACTION_REASON_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_REASON_OK\x10\x01\x12-\n" +
	")ACTION_REASON_TOO_MANY_UNAVAILABLE_VDISKS\x10\x02\x12:\n" +
	"6ACTION_REASON_TOO_MANY_UNAVAILABLE_STATE_STORAGE_RINGS\x10\x03\x12.\n" +
	"*ACTION_REASON_DISABLED_NODES_LIMIT_REACHED\x10\x04\x125\n" +
	"1ACTION_REASON_TENANT_DISABLED_NODES_LIMIT_REACHED\x10\x05\x12\x1f\n" +
	"\x1bACTION_REASON_WRONG_REQUEST\x10\x06\x120\n" +
	",ACTION_REASON_SYS_TABLETS_NODE_LIMIT_REACHED\x10\a\x12\x19\n" +
	"\x15ACTION_REASON_GENERIC\x10\b\"V\n" +
	"\x11ActionGroupStates\x12A\n" +
	"\raction_states\x18\x01 \x03(\v2\x1c.Ydb.Maintenance.ActionStateR\factionStates\"\xd8\x01\n" +
	"\x15MaintenanceTaskResult\x12\x19\n" +
	"\btask_uid\x18\x01 \x01(\tR\ataskUid\x12R\n" +
	"\x13action_group_states\x18\x02 \x03(\v2\".Ydb.Maintenance.ActionGroupStatesR\x11actionGroupStates\x12@\n" +
	"\vretry_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"retryAfter\x88\x01\x01B\x0e\n" +
	"\f_retry_after\"R\n" +
	"\x17MaintenanceTaskResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x8b\x01\n" +
	"\x19GetMaintenanceTaskRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12\"\n" +
	"\btask_uid\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\ataskUid\"\xba\x01\n" +
	"\x18GetMaintenanceTaskResult\x12J\n" +
	"\ftask_options\x18\x01 \x01(\v2'.Ydb.Maintenance.MaintenanceTaskOptionsR\vtaskOptions\x12R\n" +
	"\x13action_group_states\x18\x02 \x03(\v2\".Ydb.Maintenance.ActionGroupStatesR\x11actionGroupStates\"U\n" +
	"\x1aGetMaintenanceTaskResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x8b\x01\n" +
	"\x1bListMaintenanceTasksRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12\x17\n" +
	"\x04user\x18\x02 \x01(\tH\x00R\x04user\x88\x01\x01B\a\n" +
	"\x05_user\";\n" +
	"\x1aListMaintenanceTasksResult\x12\x1d\n" +
	"\n" +
	"tasks_uids\x18\x01 \x03(\tR\ttasksUids\"W\n" +
	"\x1cListMaintenanceTasksResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x8c\x01\n" +
	"\x1aDropMaintenanceTaskRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12\"\n" +
	"\btask_uid\x18\x02 \x01(\tB\a\xa2\xe6*\x03\x18\x80\x01R\ataskUid\"X\n" +
	"\x1dManageMaintenanceTaskResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\xa8\x01\n" +
	"\x15CompleteActionRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12C\n" +
	"\vaction_uids\x18\x02 \x03(\v2\x1a.Ydb.Maintenance.ActionUidB\x06\x9a\xe6*\x02(\x01R\n" +
	"actionUids\"\xe1\x01\n" +
	"\x12ManageActionResult\x12S\n" +
	"\x0faction_statuses\x18\x01 \x03(\v2*.Ydb.Maintenance.ManageActionResult.StatusR\x0eactionStatuses\x1av\n" +
	"\x06Status\x129\n" +
	"\n" +
	"action_uid\x18\x01 \x01(\v2\x1a.Ydb.Maintenance.ActionUidR\tactionUid\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.Ydb.StatusIds.StatusCodeR\x06status\"O\n" +
	"\x14ManageActionResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation*k\n" +
	"\tItemState\x12\x1a\n" +
	"\x16ITEM_STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rITEM_STATE_UP\x10\x01\x12\x1a\n" +
	"\x16ITEM_STATE_MAINTENANCE\x10\x02\x12\x13\n" +
	"\x0fITEM_STATE_DOWN\x10\x03*\x8c\x01\n" +
	"\x10AvailabilityMode\x12!\n" +
	"\x1dAVAILABILITY_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AVAILABILITY_MODE_STRONG\x10\x01\x12\x1a\n" +
	"\x16AVAILABILITY_MODE_WEAK\x10\x02\x12\x1b\n" +
	"\x17AVAILABILITY_MODE_FORCE\x10\x03Bn\n" +
	"#tech.ydb.proto.draft.maintenance.v1ZDgithub.com/ydb-platform/ydb-go-genproto/draft/protos/Ydb_Maintenance\xf8\x01\x01b\x06proto3"

var file_draft_protos_ydb_maintenance_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_draft_protos_ydb_maintenance_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_draft_protos_ydb_maintenance_proto_goTypes = []any{
	(ItemState)(0),                         // 0: Ydb.Maintenance.ItemState
	(AvailabilityMode)(0),                  // 1: Ydb.Maintenance.AvailabilityMode
	(ActionState_ActionStatus)(0),          // 2: Ydb.Maintenance.ActionState.ActionStatus
	(ActionState_ActionReason)(0),          // 3: Ydb.Maintenance.ActionState.ActionReason
	(*Node)(nil),                           // 4: Ydb.Maintenance.Node
	(*ListClusterNodesRequest)(nil),        // 5: Ydb.Maintenance.ListClusterNodesRequest
	(*ListClusterNodesResult)(nil),         // 6: Ydb.Maintenance.ListClusterNodesResult
	(*ListClusterNodesResponse)(nil),       // 7: Ydb.Maintenance.ListClusterNodesResponse
	(*MaintenanceTaskOptions)(nil),         // 8: Ydb.Maintenance.MaintenanceTaskOptions
	(*ActionScope)(nil),                    // 9: Ydb.Maintenance.ActionScope
	(*LockAction)(nil),                     // 10: Ydb.Maintenance.LockAction
	(*Action)(nil),                         // 11: Ydb.Maintenance.Action
	(*ActionGroup)(nil),                    // 12: Ydb.Maintenance.ActionGroup
	(*CreateMaintenanceTaskRequest)(nil),   // 13: Ydb.Maintenance.CreateMaintenanceTaskRequest
	(*RefreshMaintenanceTaskRequest)(nil),  // 14: Ydb.Maintenance.RefreshMaintenanceTaskRequest
	(*ActionUid)(nil),                      // 15: Ydb.Maintenance.ActionUid
	(*ActionState)(nil),                    // 16: Ydb.Maintenance.ActionState
	(*ActionGroupStates)(nil),              // 17: Ydb.Maintenance.ActionGroupStates
	(*MaintenanceTaskResult)(nil),          // 18: Ydb.Maintenance.MaintenanceTaskResult
	(*MaintenanceTaskResponse)(nil),        // 19: Ydb.Maintenance.MaintenanceTaskResponse
	(*GetMaintenanceTaskRequest)(nil),      // 20: Ydb.Maintenance.GetMaintenanceTaskRequest
	(*GetMaintenanceTaskResult)(nil),       // 21: Ydb.Maintenance.GetMaintenanceTaskResult
	(*GetMaintenanceTaskResponse)(nil),     // 22: Ydb.Maintenance.GetMaintenanceTaskResponse
	(*ListMaintenanceTasksRequest)(nil),    // 23: Ydb.Maintenance.ListMaintenanceTasksRequest
	(*ListMaintenanceTasksResult)(nil),     // 24: Ydb.Maintenance.ListMaintenanceTasksResult
	(*ListMaintenanceTasksResponse)(nil),   // 25: Ydb.Maintenance.ListMaintenanceTasksResponse
	(*DropMaintenanceTaskRequest)(nil),     // 26: Ydb.Maintenance.DropMaintenanceTaskRequest
	(*ManageMaintenanceTaskResponse)(nil),  // 27: Ydb.Maintenance.ManageMaintenanceTaskResponse
	(*CompleteActionRequest)(nil),          // 28: Ydb.Maintenance.CompleteActionRequest
	(*ManageActionResult)(nil),             // 29: Ydb.Maintenance.ManageActionResult
	(*ManageActionResponse)(nil),           // 30: Ydb.Maintenance.ManageActionResponse
	(*Node_StorageNode)(nil),               // 31: Ydb.Maintenance.Node.StorageNode
	(*Node_DynamicNode)(nil),               // 32: Ydb.Maintenance.Node.DynamicNode
	(*ManageActionResult_Status)(nil),      // 33: Ydb.Maintenance.ManageActionResult.Status
	(*Ydb_Discovery.NodeLocation)(nil),     // 34: Ydb.Discovery.NodeLocation
	(*timestamppb.Timestamp)(nil),          // 35: google.protobuf.Timestamp
	(*Ydb_Operations.OperationParams)(nil), // 36: Ydb.Operations.OperationParams
	(*Ydb_Operations.Operation)(nil),       // 37: Ydb.Operations.Operation
	(*durationpb.Duration)(nil),            // 38: google.protobuf.Duration
	(Ydb.StatusIds_StatusCode)(0),          // 39: Ydb.StatusIds.StatusCode
}
var file_draft_protos_ydb_maintenance_proto_depIdxs = []int32{
	34, // 0: Ydb.Maintenance.Node.location:type_name -> Ydb.Discovery.NodeLocation
	0,  // 1: Ydb.Maintenance.Node.state:type_name -> Ydb.Maintenance.ItemState
	31, // 2: Ydb.Maintenance.Node.storage:type_name -> Ydb.Maintenance.Node.StorageNode
	32, // 3: Ydb.Maintenance.Node.dynamic:type_name -> Ydb.Maintenance.Node.DynamicNode
	35, // 4: Ydb.Maintenance.Node.start_time:type_name -> google.protobuf.Timestamp
	36, // 5: Ydb.Maintenance.ListClusterNodesRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	4,  // 6: Ydb.Maintenance.ListClusterNodesResult.nodes:type_name -> Ydb.Maintenance.Node
	37, // 7: Ydb.Maintenance.ListClusterNodesResponse.operation:type_name -> Ydb.Operations.Operation
	1,  // 8: Ydb.Maintenance.MaintenanceTaskOptions.availability_mode:type_name -> Ydb.Maintenance.AvailabilityMode
	9,  // 9: Ydb.Maintenance.LockAction.scope:type_name -> Ydb.Maintenance.ActionScope
	38, // 10: Ydb.Maintenance.LockAction.duration:type_name -> google.protobuf.Duration
	10, // 11: Ydb.Maintenance.Action.lock_action:type_name -> Ydb.Maintenance.LockAction
	11, // 12: Ydb.Maintenance.ActionGroup.actions:type_name -> Ydb.Maintenance.Action
	36, // 13: Ydb.Maintenance.CreateMaintenanceTaskRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	8,  // 14: Ydb.Maintenance.CreateMaintenanceTaskRequest.task_options:type_name -> Ydb.Maintenance.MaintenanceTaskOptions
	12, // 15: Ydb.Maintenance.CreateMaintenanceTaskRequest.action_groups:type_name -> Ydb.Maintenance.ActionGroup
	36, // 16: Ydb.Maintenance.RefreshMaintenanceTaskRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	11, // 17: Ydb.Maintenance.ActionState.action:type_name -> Ydb.Maintenance.Action
	15, // 18: Ydb.Maintenance.ActionState.action_uid:type_name -> Ydb.Maintenance.ActionUid
	2,  // 19: Ydb.Maintenance.ActionState.status:type_name -> Ydb.Maintenance.ActionState.ActionStatus
	3,  // 20: Ydb.Maintenance.ActionState.reason:type_name -> Ydb.Maintenance.ActionState.ActionReason
	35, // 21: Ydb.Maintenance.ActionState.deadline:type_name -> google.protobuf.Timestamp
	16, // 22: Ydb.Maintenance.ActionGroupStates.action_states:type_name -> Ydb.Maintenance.ActionState
	17, // 23: Ydb.Maintenance.MaintenanceTaskResult.action_group_states:type_name -> Ydb.Maintenance.ActionGroupStates
	35, // 24: Ydb.Maintenance.MaintenanceTaskResult.retry_after:type_name -> google.protobuf.Timestamp
	37, // 25: Ydb.Maintenance.MaintenanceTaskResponse.operation:type_name -> Ydb.Operations.Operation
	36, // 26: Ydb.Maintenance.GetMaintenanceTaskRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	8,  // 27: Ydb.Maintenance.GetMaintenanceTaskResult.task_options:type_name -> Ydb.Maintenance.MaintenanceTaskOptions
	17, // 28: Ydb.Maintenance.GetMaintenanceTaskResult.action_group_states:type_name -> Ydb.Maintenance.ActionGroupStates
	37, // 29: Ydb.Maintenance.GetMaintenanceTaskResponse.operation:type_name -> Ydb.Operations.Operation
	36, // 30: Ydb.Maintenance.ListMaintenanceTasksRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	37, // 31: Ydb.Maintenance.ListMaintenanceTasksResponse.operation:type_name -> Ydb.Operations.Operation
	36, // 32: Ydb.Maintenance.DropMaintenanceTaskRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	37, // 33: Ydb.Maintenance.ManageMaintenanceTaskResponse.operation:type_name -> Ydb.Operations.Operation
	36, // 34: Ydb.Maintenance.CompleteActionRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	15, // 35: Ydb.Maintenance.CompleteActionRequest.action_uids:type_name -> Ydb.Maintenance.ActionUid
	33, // 36: Ydb.Maintenance.ManageActionResult.action_statuses:type_name -> Ydb.Maintenance.ManageActionResult.Status
	37, // 37: Ydb.Maintenance.ManageActionResponse.operation:type_name -> Ydb.Operations.Operation
	15, // 38: Ydb.Maintenance.ManageActionResult.Status.action_uid:type_name -> Ydb.Maintenance.ActionUid
	39, // 39: Ydb.Maintenance.ManageActionResult.Status.status:type_name -> Ydb.StatusIds.StatusCode
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_draft_protos_ydb_maintenance_proto_init() }
func file_draft_protos_ydb_maintenance_proto_init() {
	if File_draft_protos_ydb_maintenance_proto != nil {
		return
	}
	file_draft_protos_ydb_maintenance_proto_msgTypes[0].OneofWrappers = []any{
		(*node_Storage)(nil),
		(*node_Dynamic)(nil),
	}
	file_draft_protos_ydb_maintenance_proto_msgTypes[5].OneofWrappers = []any{
		(*actionScope_NodeId)(nil),
		(*actionScope_Host)(nil),
	}
	file_draft_protos_ydb_maintenance_proto_msgTypes[7].OneofWrappers = []any{
		(*action_LockAction)(nil),
	}
	file_draft_protos_ydb_maintenance_proto_msgTypes[14].OneofWrappers = []any{}
	file_draft_protos_ydb_maintenance_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draft_protos_ydb_maintenance_proto_rawDesc), len(file_draft_protos_ydb_maintenance_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draft_protos_ydb_maintenance_proto_goTypes,
		DependencyIndexes: file_draft_protos_ydb_maintenance_proto_depIdxs,
		EnumInfos:         file_draft_protos_ydb_maintenance_proto_enumTypes,
		MessageInfos:      file_draft_protos_ydb_maintenance_proto_msgTypes,
	}.Build()
	File_draft_protos_ydb_maintenance_proto = out.File
	file_draft_protos_ydb_maintenance_proto_goTypes = nil
	file_draft_protos_ydb_maintenance_proto_depIdxs = nil
}
