// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/ydb_common.proto

//go:build protoopaque

package Ydb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureFlag_Status int32

const (
	FeatureFlag_STATUS_UNSPECIFIED FeatureFlag_Status = 0
	FeatureFlag_ENABLED            FeatureFlag_Status = 1
	FeatureFlag_DISABLED           FeatureFlag_Status = 2
)

// Enum value maps for FeatureFlag_Status.
var (
	FeatureFlag_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "ENABLED",
		2: "DISABLED",
	}
	FeatureFlag_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"ENABLED":            1,
		"DISABLED":           2,
	}
)

func (x FeatureFlag_Status) Enum() *FeatureFlag_Status {
	p := new(FeatureFlag_Status)
	*p = x
	return p
}

func (x FeatureFlag_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureFlag_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ydb_common_proto_enumTypes[0].Descriptor()
}

func (FeatureFlag_Status) Type() protoreflect.EnumType {
	return &file_protos_ydb_common_proto_enumTypes[0]
}

func (x FeatureFlag_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_protos_ydb_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FeatureFlag_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FeatureFlag_builder) Build() *FeatureFlag {
	m0 := &FeatureFlag{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CostInfo struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConsumedUnits float64                `protobuf:"fixed64,1,opt,name=consumed_units,json=consumedUnits"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CostInfo) Reset() {
	*x = CostInfo{}
	mi := &file_protos_ydb_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostInfo) ProtoMessage() {}

func (x *CostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CostInfo) GetConsumedUnits() float64 {
	if x != nil {
		return x.xxx_hidden_ConsumedUnits
	}
	return 0
}

func (x *CostInfo) SetConsumedUnits(v float64) {
	x.xxx_hidden_ConsumedUnits = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CostInfo) HasConsumedUnits() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CostInfo) ClearConsumedUnits() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ConsumedUnits = 0
}

type CostInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Total amount of request units (RU), consumed by the operation.
	ConsumedUnits *float64
}

func (b0 CostInfo_builder) Build() *CostInfo {
	m0 := &CostInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ConsumedUnits != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ConsumedUnits = *b.ConsumedUnits
	}
	return m0
}

type QuotaExceeded struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disk        bool                   `protobuf:"varint,1,opt,name=disk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QuotaExceeded) Reset() {
	*x = QuotaExceeded{}
	mi := &file_protos_ydb_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaExceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaExceeded) ProtoMessage() {}

func (x *QuotaExceeded) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QuotaExceeded) GetDisk() bool {
	if x != nil {
		return x.xxx_hidden_Disk
	}
	return false
}

func (x *QuotaExceeded) SetDisk(v bool) {
	x.xxx_hidden_Disk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *QuotaExceeded) HasDisk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *QuotaExceeded) ClearDisk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disk = false
}

type QuotaExceeded_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disk *bool
}

func (b0 QuotaExceeded_builder) Build() *QuotaExceeded {
	m0 := &QuotaExceeded{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Disk = *b.Disk
	}
	return m0
}

// Specifies a point in database time
type VirtualTimestamp struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PlanStep    uint64                 `protobuf:"varint,1,opt,name=plan_step,json=planStep"`
	xxx_hidden_TxId        uint64                 `protobuf:"varint,2,opt,name=tx_id,json=txId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VirtualTimestamp) Reset() {
	*x = VirtualTimestamp{}
	mi := &file_protos_ydb_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualTimestamp) ProtoMessage() {}

func (x *VirtualTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VirtualTimestamp) GetPlanStep() uint64 {
	if x != nil {
		return x.xxx_hidden_PlanStep
	}
	return 0
}

func (x *VirtualTimestamp) GetTxId() uint64 {
	if x != nil {
		return x.xxx_hidden_TxId
	}
	return 0
}

func (x *VirtualTimestamp) SetPlanStep(v uint64) {
	x.xxx_hidden_PlanStep = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *VirtualTimestamp) SetTxId(v uint64) {
	x.xxx_hidden_TxId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *VirtualTimestamp) HasPlanStep() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VirtualTimestamp) HasTxId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VirtualTimestamp) ClearPlanStep() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PlanStep = 0
}

func (x *VirtualTimestamp) ClearTxId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TxId = 0
}

type VirtualTimestamp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PlanStep *uint64
	TxId     *uint64
}

func (b0 VirtualTimestamp_builder) Build() *VirtualTimestamp {
	m0 := &VirtualTimestamp{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PlanStep != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PlanStep = *b.PlanStep
	}
	if b.TxId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TxId = *b.TxId
	}
	return m0
}

var File_protos_ydb_common_proto protoreflect.FileDescriptor

const file_protos_ydb_common_proto_rawDesc = "" +
	"\n" +
	"\x17protos/ydb_common.proto\x12\x03Ydb\x1a!google/protobuf/go_features.proto\"J\n" +
	"\vFeatureFlag\";\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02\"1\n" +
	"\bCostInfo\x12%\n" +
	"\x0econsumed_units\x18\x01 \x01(\x01R\rconsumedUnits\"#\n" +
	"\rQuotaExceeded\x12\x12\n" +
	"\x04disk\x18\x01 \x01(\bR\x04disk\"D\n" +
	"\x10VirtualTimestamp\x12\x1b\n" +
	"\tplan_step\x18\x01 \x01(\x04R\bplanStep\x12\x13\n" +
	"\x05tx_id\x18\x02 \x01(\x04R\x04txIdBd\n" +
	"\x15tech.ydb.proto.commonB\fCommonProtosZ2github.com/ydb-platform/ydb-go-genproto/protos/Ydb\xf8\x01\x01\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_protos_ydb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_ydb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_ydb_common_proto_goTypes = []any{
	(FeatureFlag_Status)(0),  // 0: Ydb.FeatureFlag.Status
	(*FeatureFlag)(nil),      // 1: Ydb.FeatureFlag
	(*CostInfo)(nil),         // 2: Ydb.CostInfo
	(*QuotaExceeded)(nil),    // 3: Ydb.QuotaExceeded
	(*VirtualTimestamp)(nil), // 4: Ydb.VirtualTimestamp
}
var file_protos_ydb_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ydb_common_proto_init() }
func file_protos_ydb_common_proto_init() {
	if File_protos_ydb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_common_proto_rawDesc), len(file_protos_ydb_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_common_proto_goTypes,
		DependencyIndexes: file_protos_ydb_common_proto_depIdxs,
		EnumInfos:         file_protos_ydb_common_proto_enumTypes,
		MessageInfos:      file_protos_ydb_common_proto_msgTypes,
	}.Build()
	File_protos_ydb_common_proto = out.File
	file_protos_ydb_common_proto_goTypes = nil
	file_protos_ydb_common_proto_depIdxs = nil
}
