// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: protos/ydb_query_stats.proto

package Ydb_TableStats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes select, update (insert, upsert, replace) and delete operations
type OperationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint64                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStats) Reset() {
	*x = OperationStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStats) ProtoMessage() {}

func (x *OperationStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStats.ProtoReflect.Descriptor instead.
func (*OperationStats) Descriptor() ([]byte, []int) {
	return file_protos_ydb_query_stats_proto_rawDescGZIP(), []int{0}
}

func (x *OperationStats) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *OperationStats) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

// Describes all operations on a table
type TableAccessStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reads           *OperationStats        `protobuf:"bytes,3,opt,name=reads,proto3" json:"reads,omitempty"`
	Updates         *OperationStats        `protobuf:"bytes,4,opt,name=updates,proto3" json:"updates,omitempty"`
	Deletes         *OperationStats        `protobuf:"bytes,5,opt,name=deletes,proto3" json:"deletes,omitempty"`
	PartitionsCount uint64                 `protobuf:"varint,6,opt,name=partitions_count,json=partitionsCount,proto3" json:"partitions_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableAccessStats) Reset() {
	*x = TableAccessStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAccessStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAccessStats) ProtoMessage() {}

func (x *TableAccessStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAccessStats.ProtoReflect.Descriptor instead.
func (*TableAccessStats) Descriptor() ([]byte, []int) {
	return file_protos_ydb_query_stats_proto_rawDescGZIP(), []int{1}
}

func (x *TableAccessStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableAccessStats) GetReads() *OperationStats {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *TableAccessStats) GetUpdates() *OperationStats {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *TableAccessStats) GetDeletes() *OperationStats {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *TableAccessStats) GetPartitionsCount() uint64 {
	if x != nil {
		return x.PartitionsCount
	}
	return 0
}

type QueryPhaseStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DurationUs     uint64                 `protobuf:"varint,1,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	TableAccess    []*TableAccessStats    `protobuf:"bytes,2,rep,name=table_access,json=tableAccess,proto3" json:"table_access,omitempty"`
	CpuTimeUs      uint64                 `protobuf:"varint,3,opt,name=cpu_time_us,json=cpuTimeUs,proto3" json:"cpu_time_us,omitempty"`
	AffectedShards uint64                 `protobuf:"varint,4,opt,name=affected_shards,json=affectedShards,proto3" json:"affected_shards,omitempty"`
	LiteralPhase   bool                   `protobuf:"varint,5,opt,name=literal_phase,json=literalPhase,proto3" json:"literal_phase,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryPhaseStats) Reset() {
	*x = QueryPhaseStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPhaseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhaseStats) ProtoMessage() {}

func (x *QueryPhaseStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPhaseStats.ProtoReflect.Descriptor instead.
func (*QueryPhaseStats) Descriptor() ([]byte, []int) {
	return file_protos_ydb_query_stats_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPhaseStats) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *QueryPhaseStats) GetTableAccess() []*TableAccessStats {
	if x != nil {
		return x.TableAccess
	}
	return nil
}

func (x *QueryPhaseStats) GetCpuTimeUs() uint64 {
	if x != nil {
		return x.CpuTimeUs
	}
	return 0
}

func (x *QueryPhaseStats) GetAffectedShards() uint64 {
	if x != nil {
		return x.AffectedShards
	}
	return 0
}

func (x *QueryPhaseStats) GetLiteralPhase() bool {
	if x != nil {
		return x.LiteralPhase
	}
	return false
}

type CompilationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCache     bool                   `protobuf:"varint,1,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	DurationUs    uint64                 `protobuf:"varint,2,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	CpuTimeUs     uint64                 `protobuf:"varint,3,opt,name=cpu_time_us,json=cpuTimeUs,proto3" json:"cpu_time_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompilationStats) Reset() {
	*x = CompilationStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationStats) ProtoMessage() {}

func (x *CompilationStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationStats.ProtoReflect.Descriptor instead.
func (*CompilationStats) Descriptor() ([]byte, []int) {
	return file_protos_ydb_query_stats_proto_rawDescGZIP(), []int{3}
}

func (x *CompilationStats) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *CompilationStats) GetDurationUs() uint64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

func (x *CompilationStats) GetCpuTimeUs() uint64 {
	if x != nil {
		return x.CpuTimeUs
	}
	return 0
}

type QueryStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A query might have one or more execution phases
	QueryPhases      []*QueryPhaseStats `protobuf:"bytes,1,rep,name=query_phases,json=queryPhases,proto3" json:"query_phases,omitempty"`
	Compilation      *CompilationStats  `protobuf:"bytes,2,opt,name=compilation,proto3" json:"compilation,omitempty"`
	ProcessCpuTimeUs uint64             `protobuf:"varint,3,opt,name=process_cpu_time_us,json=processCpuTimeUs,proto3" json:"process_cpu_time_us,omitempty"`
	QueryPlan        string             `protobuf:"bytes,4,opt,name=query_plan,json=queryPlan,proto3" json:"query_plan,omitempty"`
	QueryAst         string             `protobuf:"bytes,5,opt,name=query_ast,json=queryAst,proto3" json:"query_ast,omitempty"`
	TotalDurationUs  uint64             `protobuf:"varint,6,opt,name=total_duration_us,json=totalDurationUs,proto3" json:"total_duration_us,omitempty"`
	TotalCpuTimeUs   uint64             `protobuf:"varint,7,opt,name=total_cpu_time_us,json=totalCpuTimeUs,proto3" json:"total_cpu_time_us,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStats.ProtoReflect.Descriptor instead.
func (*QueryStats) Descriptor() ([]byte, []int) {
	return file_protos_ydb_query_stats_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStats) GetQueryPhases() []*QueryPhaseStats {
	if x != nil {
		return x.QueryPhases
	}
	return nil
}

func (x *QueryStats) GetCompilation() *CompilationStats {
	if x != nil {
		return x.Compilation
	}
	return nil
}

func (x *QueryStats) GetProcessCpuTimeUs() uint64 {
	if x != nil {
		return x.ProcessCpuTimeUs
	}
	return 0
}

func (x *QueryStats) GetQueryPlan() string {
	if x != nil {
		return x.QueryPlan
	}
	return ""
}

func (x *QueryStats) GetQueryAst() string {
	if x != nil {
		return x.QueryAst
	}
	return ""
}

func (x *QueryStats) GetTotalDurationUs() uint64 {
	if x != nil {
		return x.TotalDurationUs
	}
	return 0
}

func (x *QueryStats) GetTotalCpuTimeUs() uint64 {
	if x != nil {
		return x.TotalCpuTimeUs
	}
	return 0
}

var File_protos_ydb_query_stats_proto protoreflect.FileDescriptor

const file_protos_ydb_query_stats_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/ydb_query_stats.proto\x12\x0eYdb.TableStats\":\n" +
	"\x0eOperationStats\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\"\x81\x02\n" +
	"\x10TableAccessStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x05reads\x18\x03 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\x05reads\x128\n" +
	"\aupdates\x18\x04 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\aupdates\x128\n" +
	"\adeletes\x18\x05 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\adeletes\x12)\n" +
	"\x10partitions_count\x18\x06 \x01(\x04R\x0fpartitionsCountJ\x04\b\x02\x10\x03\"\xe5\x01\n" +
	"\x0fQueryPhaseStats\x12\x1f\n" +
	"\vduration_us\x18\x01 \x01(\x04R\n" +
	"durationUs\x12C\n" +
	"\ftable_access\x18\x02 \x03(\v2 .Ydb.TableStats.TableAccessStatsR\vtableAccess\x12\x1e\n" +
	"\vcpu_time_us\x18\x03 \x01(\x04R\tcpuTimeUs\x12'\n" +
	"\x0faffected_shards\x18\x04 \x01(\x04R\x0eaffectedShards\x12#\n" +
	"\rliteral_phase\x18\x05 \x01(\bR\fliteralPhase\"r\n" +
	"\x10CompilationStats\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x01 \x01(\bR\tfromCache\x12\x1f\n" +
	"\vduration_us\x18\x02 \x01(\x04R\n" +
	"durationUs\x12\x1e\n" +
	"\vcpu_time_us\x18\x03 \x01(\x04R\tcpuTimeUs\"\xd6\x02\n" +
	"\n" +
	"QueryStats\x12B\n" +
	"\fquery_phases\x18\x01 \x03(\v2\x1f.Ydb.TableStats.QueryPhaseStatsR\vqueryPhases\x12B\n" +
	"\vcompilation\x18\x02 \x01(\v2 .Ydb.TableStats.CompilationStatsR\vcompilation\x12-\n" +
	"\x13process_cpu_time_us\x18\x03 \x01(\x04R\x10processCpuTimeUs\x12\x1d\n" +
	"\n" +
	"query_plan\x18\x04 \x01(\tR\tqueryPlan\x12\x1b\n" +
	"\tquery_ast\x18\x05 \x01(\tR\bqueryAst\x12*\n" +
	"\x11total_duration_us\x18\x06 \x01(\x04R\x0ftotalDurationUs\x12)\n" +
	"\x11total_cpu_time_us\x18\a \x01(\x04R\x0etotalCpuTimeUsBR\n" +
	"\x0etech.ydb.protoZ=github.com/ydb-platform/ydb-go-genproto/protos/Ydb_TableStats\xf8\x01\x01b\x06proto3"

var (
	file_protos_ydb_query_stats_proto_rawDescOnce sync.Once
	file_protos_ydb_query_stats_proto_rawDescData []byte
)

func file_protos_ydb_query_stats_proto_rawDescGZIP() []byte {
	file_protos_ydb_query_stats_proto_rawDescOnce.Do(func() {
		file_protos_ydb_query_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ydb_query_stats_proto_rawDesc), len(file_protos_ydb_query_stats_proto_rawDesc)))
	})
	return file_protos_ydb_query_stats_proto_rawDescData
}

var file_protos_ydb_query_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_ydb_query_stats_proto_goTypes = []any{
	(*OperationStats)(nil),   // 0: Ydb.TableStats.OperationStats
	(*TableAccessStats)(nil), // 1: Ydb.TableStats.TableAccessStats
	(*QueryPhaseStats)(nil),  // 2: Ydb.TableStats.QueryPhaseStats
	(*CompilationStats)(nil), // 3: Ydb.TableStats.CompilationStats
	(*QueryStats)(nil),       // 4: Ydb.TableStats.QueryStats
}
var file_protos_ydb_query_stats_proto_depIdxs = []int32{
	0, // 0: Ydb.TableStats.TableAccessStats.reads:type_name -> Ydb.TableStats.OperationStats
	0, // 1: Ydb.TableStats.TableAccessStats.updates:type_name -> Ydb.TableStats.OperationStats
	0, // 2: Ydb.TableStats.TableAccessStats.deletes:type_name -> Ydb.TableStats.OperationStats
	1, // 3: Ydb.TableStats.QueryPhaseStats.table_access:type_name -> Ydb.TableStats.TableAccessStats
	2, // 4: Ydb.TableStats.QueryStats.query_phases:type_name -> Ydb.TableStats.QueryPhaseStats
	3, // 5: Ydb.TableStats.QueryStats.compilation:type_name -> Ydb.TableStats.CompilationStats
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_ydb_query_stats_proto_init() }
func file_protos_ydb_query_stats_proto_init() {
	if File_protos_ydb_query_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_query_stats_proto_rawDesc), len(file_protos_ydb_query_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_query_stats_proto_goTypes,
		DependencyIndexes: file_protos_ydb_query_stats_proto_depIdxs,
		MessageInfos:      file_protos_ydb_query_stats_proto_msgTypes,
	}.Build()
	File_protos_ydb_query_stats_proto = out.File
	file_protos_ydb_query_stats_proto_goTypes = nil
	file_protos_ydb_query_stats_proto_depIdxs = nil
}
