// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/ydb_query_stats.proto

//go:build protoopaque

package Ydb_TableStats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes select, update (insert, upsert, replace) and delete operations
type OperationStats struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Rows        uint64                 `protobuf:"varint,1,opt,name=rows"`
	xxx_hidden_Bytes       uint64                 `protobuf:"varint,2,opt,name=bytes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OperationStats) Reset() {
	*x = OperationStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStats) ProtoMessage() {}

func (x *OperationStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperationStats) GetRows() uint64 {
	if x != nil {
		return x.xxx_hidden_Rows
	}
	return 0
}

func (x *OperationStats) GetBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_Bytes
	}
	return 0
}

func (x *OperationStats) SetRows(v uint64) {
	x.xxx_hidden_Rows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OperationStats) SetBytes(v uint64) {
	x.xxx_hidden_Bytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OperationStats) HasRows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OperationStats) HasBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OperationStats) ClearRows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Rows = 0
}

func (x *OperationStats) ClearBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Bytes = 0
}

type OperationStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Rows  *uint64
	Bytes *uint64
}

func (b0 OperationStats_builder) Build() *OperationStats {
	m0 := &OperationStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Rows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Rows = *b.Rows
	}
	if b.Bytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Bytes = *b.Bytes
	}
	return m0
}

// Describes all operations on a table
type TableAccessStats struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name            *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Reads           *OperationStats        `protobuf:"bytes,3,opt,name=reads"`
	xxx_hidden_Updates         *OperationStats        `protobuf:"bytes,4,opt,name=updates"`
	xxx_hidden_Deletes         *OperationStats        `protobuf:"bytes,5,opt,name=deletes"`
	xxx_hidden_PartitionsCount uint64                 `protobuf:"varint,6,opt,name=partitions_count,json=partitionsCount"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TableAccessStats) Reset() {
	*x = TableAccessStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAccessStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAccessStats) ProtoMessage() {}

func (x *TableAccessStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TableAccessStats) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *TableAccessStats) GetReads() *OperationStats {
	if x != nil {
		return x.xxx_hidden_Reads
	}
	return nil
}

func (x *TableAccessStats) GetUpdates() *OperationStats {
	if x != nil {
		return x.xxx_hidden_Updates
	}
	return nil
}

func (x *TableAccessStats) GetDeletes() *OperationStats {
	if x != nil {
		return x.xxx_hidden_Deletes
	}
	return nil
}

func (x *TableAccessStats) GetPartitionsCount() uint64 {
	if x != nil {
		return x.xxx_hidden_PartitionsCount
	}
	return 0
}

func (x *TableAccessStats) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *TableAccessStats) SetReads(v *OperationStats) {
	x.xxx_hidden_Reads = v
}

func (x *TableAccessStats) SetUpdates(v *OperationStats) {
	x.xxx_hidden_Updates = v
}

func (x *TableAccessStats) SetDeletes(v *OperationStats) {
	x.xxx_hidden_Deletes = v
}

func (x *TableAccessStats) SetPartitionsCount(v uint64) {
	x.xxx_hidden_PartitionsCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *TableAccessStats) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TableAccessStats) HasReads() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Reads != nil
}

func (x *TableAccessStats) HasUpdates() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updates != nil
}

func (x *TableAccessStats) HasDeletes() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Deletes != nil
}

func (x *TableAccessStats) HasPartitionsCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TableAccessStats) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *TableAccessStats) ClearReads() {
	x.xxx_hidden_Reads = nil
}

func (x *TableAccessStats) ClearUpdates() {
	x.xxx_hidden_Updates = nil
}

func (x *TableAccessStats) ClearDeletes() {
	x.xxx_hidden_Deletes = nil
}

func (x *TableAccessStats) ClearPartitionsCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PartitionsCount = 0
}

type TableAccessStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name            *string
	Reads           *OperationStats
	Updates         *OperationStats
	Deletes         *OperationStats
	PartitionsCount *uint64
}

func (b0 TableAccessStats_builder) Build() *TableAccessStats {
	m0 := &TableAccessStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Reads = b.Reads
	x.xxx_hidden_Updates = b.Updates
	x.xxx_hidden_Deletes = b.Deletes
	if b.PartitionsCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_PartitionsCount = *b.PartitionsCount
	}
	return m0
}

type QueryPhaseStats struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DurationUs     uint64                 `protobuf:"varint,1,opt,name=duration_us,json=durationUs"`
	xxx_hidden_TableAccess    *[]*TableAccessStats   `protobuf:"bytes,2,rep,name=table_access,json=tableAccess"`
	xxx_hidden_CpuTimeUs      uint64                 `protobuf:"varint,3,opt,name=cpu_time_us,json=cpuTimeUs"`
	xxx_hidden_AffectedShards uint64                 `protobuf:"varint,4,opt,name=affected_shards,json=affectedShards"`
	xxx_hidden_LiteralPhase   bool                   `protobuf:"varint,5,opt,name=literal_phase,json=literalPhase"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *QueryPhaseStats) Reset() {
	*x = QueryPhaseStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPhaseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhaseStats) ProtoMessage() {}

func (x *QueryPhaseStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryPhaseStats) GetDurationUs() uint64 {
	if x != nil {
		return x.xxx_hidden_DurationUs
	}
	return 0
}

func (x *QueryPhaseStats) GetTableAccess() []*TableAccessStats {
	if x != nil {
		if x.xxx_hidden_TableAccess != nil {
			return *x.xxx_hidden_TableAccess
		}
	}
	return nil
}

func (x *QueryPhaseStats) GetCpuTimeUs() uint64 {
	if x != nil {
		return x.xxx_hidden_CpuTimeUs
	}
	return 0
}

func (x *QueryPhaseStats) GetAffectedShards() uint64 {
	if x != nil {
		return x.xxx_hidden_AffectedShards
	}
	return 0
}

func (x *QueryPhaseStats) GetLiteralPhase() bool {
	if x != nil {
		return x.xxx_hidden_LiteralPhase
	}
	return false
}

func (x *QueryPhaseStats) SetDurationUs(v uint64) {
	x.xxx_hidden_DurationUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *QueryPhaseStats) SetTableAccess(v []*TableAccessStats) {
	x.xxx_hidden_TableAccess = &v
}

func (x *QueryPhaseStats) SetCpuTimeUs(v uint64) {
	x.xxx_hidden_CpuTimeUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *QueryPhaseStats) SetAffectedShards(v uint64) {
	x.xxx_hidden_AffectedShards = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *QueryPhaseStats) SetLiteralPhase(v bool) {
	x.xxx_hidden_LiteralPhase = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *QueryPhaseStats) HasDurationUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *QueryPhaseStats) HasCpuTimeUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryPhaseStats) HasAffectedShards() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *QueryPhaseStats) HasLiteralPhase() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *QueryPhaseStats) ClearDurationUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DurationUs = 0
}

func (x *QueryPhaseStats) ClearCpuTimeUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CpuTimeUs = 0
}

func (x *QueryPhaseStats) ClearAffectedShards() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AffectedShards = 0
}

func (x *QueryPhaseStats) ClearLiteralPhase() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_LiteralPhase = false
}

type QueryPhaseStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DurationUs     *uint64
	TableAccess    []*TableAccessStats
	CpuTimeUs      *uint64
	AffectedShards *uint64
	LiteralPhase   *bool
}

func (b0 QueryPhaseStats_builder) Build() *QueryPhaseStats {
	m0 := &QueryPhaseStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DurationUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_DurationUs = *b.DurationUs
	}
	x.xxx_hidden_TableAccess = &b.TableAccess
	if b.CpuTimeUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_CpuTimeUs = *b.CpuTimeUs
	}
	if b.AffectedShards != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_AffectedShards = *b.AffectedShards
	}
	if b.LiteralPhase != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_LiteralPhase = *b.LiteralPhase
	}
	return m0
}

type CompilationStats struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FromCache   bool                   `protobuf:"varint,1,opt,name=from_cache,json=fromCache"`
	xxx_hidden_DurationUs  uint64                 `protobuf:"varint,2,opt,name=duration_us,json=durationUs"`
	xxx_hidden_CpuTimeUs   uint64                 `protobuf:"varint,3,opt,name=cpu_time_us,json=cpuTimeUs"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CompilationStats) Reset() {
	*x = CompilationStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationStats) ProtoMessage() {}

func (x *CompilationStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CompilationStats) GetFromCache() bool {
	if x != nil {
		return x.xxx_hidden_FromCache
	}
	return false
}

func (x *CompilationStats) GetDurationUs() uint64 {
	if x != nil {
		return x.xxx_hidden_DurationUs
	}
	return 0
}

func (x *CompilationStats) GetCpuTimeUs() uint64 {
	if x != nil {
		return x.xxx_hidden_CpuTimeUs
	}
	return 0
}

func (x *CompilationStats) SetFromCache(v bool) {
	x.xxx_hidden_FromCache = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CompilationStats) SetDurationUs(v uint64) {
	x.xxx_hidden_DurationUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CompilationStats) SetCpuTimeUs(v uint64) {
	x.xxx_hidden_CpuTimeUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CompilationStats) HasFromCache() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CompilationStats) HasDurationUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CompilationStats) HasCpuTimeUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CompilationStats) ClearFromCache() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FromCache = false
}

func (x *CompilationStats) ClearDurationUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DurationUs = 0
}

func (x *CompilationStats) ClearCpuTimeUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CpuTimeUs = 0
}

type CompilationStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FromCache  *bool
	DurationUs *uint64
	CpuTimeUs  *uint64
}

func (b0 CompilationStats_builder) Build() *CompilationStats {
	m0 := &CompilationStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FromCache != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_FromCache = *b.FromCache
	}
	if b.DurationUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_DurationUs = *b.DurationUs
	}
	if b.CpuTimeUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CpuTimeUs = *b.CpuTimeUs
	}
	return m0
}

type QueryStats struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_QueryPhases      *[]*QueryPhaseStats    `protobuf:"bytes,1,rep,name=query_phases,json=queryPhases"`
	xxx_hidden_Compilation      *CompilationStats      `protobuf:"bytes,2,opt,name=compilation"`
	xxx_hidden_ProcessCpuTimeUs uint64                 `protobuf:"varint,3,opt,name=process_cpu_time_us,json=processCpuTimeUs"`
	xxx_hidden_QueryPlan        *string                `protobuf:"bytes,4,opt,name=query_plan,json=queryPlan"`
	xxx_hidden_QueryAst         *string                `protobuf:"bytes,5,opt,name=query_ast,json=queryAst"`
	xxx_hidden_TotalDurationUs  uint64                 `protobuf:"varint,6,opt,name=total_duration_us,json=totalDurationUs"`
	xxx_hidden_TotalCpuTimeUs   uint64                 `protobuf:"varint,7,opt,name=total_cpu_time_us,json=totalCpuTimeUs"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_protos_ydb_query_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_query_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryStats) GetQueryPhases() []*QueryPhaseStats {
	if x != nil {
		if x.xxx_hidden_QueryPhases != nil {
			return *x.xxx_hidden_QueryPhases
		}
	}
	return nil
}

func (x *QueryStats) GetCompilation() *CompilationStats {
	if x != nil {
		return x.xxx_hidden_Compilation
	}
	return nil
}

func (x *QueryStats) GetProcessCpuTimeUs() uint64 {
	if x != nil {
		return x.xxx_hidden_ProcessCpuTimeUs
	}
	return 0
}

func (x *QueryStats) GetQueryPlan() string {
	if x != nil {
		if x.xxx_hidden_QueryPlan != nil {
			return *x.xxx_hidden_QueryPlan
		}
		return ""
	}
	return ""
}

func (x *QueryStats) GetQueryAst() string {
	if x != nil {
		if x.xxx_hidden_QueryAst != nil {
			return *x.xxx_hidden_QueryAst
		}
		return ""
	}
	return ""
}

func (x *QueryStats) GetTotalDurationUs() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalDurationUs
	}
	return 0
}

func (x *QueryStats) GetTotalCpuTimeUs() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalCpuTimeUs
	}
	return 0
}

func (x *QueryStats) SetQueryPhases(v []*QueryPhaseStats) {
	x.xxx_hidden_QueryPhases = &v
}

func (x *QueryStats) SetCompilation(v *CompilationStats) {
	x.xxx_hidden_Compilation = v
}

func (x *QueryStats) SetProcessCpuTimeUs(v uint64) {
	x.xxx_hidden_ProcessCpuTimeUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *QueryStats) SetQueryPlan(v string) {
	x.xxx_hidden_QueryPlan = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *QueryStats) SetQueryAst(v string) {
	x.xxx_hidden_QueryAst = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *QueryStats) SetTotalDurationUs(v uint64) {
	x.xxx_hidden_TotalDurationUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *QueryStats) SetTotalCpuTimeUs(v uint64) {
	x.xxx_hidden_TotalCpuTimeUs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *QueryStats) HasCompilation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Compilation != nil
}

func (x *QueryStats) HasProcessCpuTimeUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryStats) HasQueryPlan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *QueryStats) HasQueryAst() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *QueryStats) HasTotalDurationUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *QueryStats) HasTotalCpuTimeUs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *QueryStats) ClearCompilation() {
	x.xxx_hidden_Compilation = nil
}

func (x *QueryStats) ClearProcessCpuTimeUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ProcessCpuTimeUs = 0
}

func (x *QueryStats) ClearQueryPlan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_QueryPlan = nil
}

func (x *QueryStats) ClearQueryAst() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_QueryAst = nil
}

func (x *QueryStats) ClearTotalDurationUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_TotalDurationUs = 0
}

func (x *QueryStats) ClearTotalCpuTimeUs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_TotalCpuTimeUs = 0
}

type QueryStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A query might have one or more execution phases
	QueryPhases      []*QueryPhaseStats
	Compilation      *CompilationStats
	ProcessCpuTimeUs *uint64
	QueryPlan        *string
	QueryAst         *string
	TotalDurationUs  *uint64
	TotalCpuTimeUs   *uint64
}

func (b0 QueryStats_builder) Build() *QueryStats {
	m0 := &QueryStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_QueryPhases = &b.QueryPhases
	x.xxx_hidden_Compilation = b.Compilation
	if b.ProcessCpuTimeUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ProcessCpuTimeUs = *b.ProcessCpuTimeUs
	}
	if b.QueryPlan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_QueryPlan = b.QueryPlan
	}
	if b.QueryAst != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_QueryAst = b.QueryAst
	}
	if b.TotalDurationUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_TotalDurationUs = *b.TotalDurationUs
	}
	if b.TotalCpuTimeUs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_TotalCpuTimeUs = *b.TotalCpuTimeUs
	}
	return m0
}

var File_protos_ydb_query_stats_proto protoreflect.FileDescriptor

const file_protos_ydb_query_stats_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/ydb_query_stats.proto\x12\x0eYdb.TableStats\x1a!google/protobuf/go_features.proto\":\n" +
	"\x0eOperationStats\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\"\x81\x02\n" +
	"\x10TableAccessStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x05reads\x18\x03 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\x05reads\x128\n" +
	"\aupdates\x18\x04 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\aupdates\x128\n" +
	"\adeletes\x18\x05 \x01(\v2\x1e.Ydb.TableStats.OperationStatsR\adeletes\x12)\n" +
	"\x10partitions_count\x18\x06 \x01(\x04R\x0fpartitionsCountJ\x04\b\x02\x10\x03\"\xe5\x01\n" +
	"\x0fQueryPhaseStats\x12\x1f\n" +
	"\vduration_us\x18\x01 \x01(\x04R\n" +
	"durationUs\x12C\n" +
	"\ftable_access\x18\x02 \x03(\v2 .Ydb.TableStats.TableAccessStatsR\vtableAccess\x12\x1e\n" +
	"\vcpu_time_us\x18\x03 \x01(\x04R\tcpuTimeUs\x12'\n" +
	"\x0faffected_shards\x18\x04 \x01(\x04R\x0eaffectedShards\x12#\n" +
	"\rliteral_phase\x18\x05 \x01(\bR\fliteralPhase\"r\n" +
	"\x10CompilationStats\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x01 \x01(\bR\tfromCache\x12\x1f\n" +
	"\vduration_us\x18\x02 \x01(\x04R\n" +
	"durationUs\x12\x1e\n" +
	"\vcpu_time_us\x18\x03 \x01(\x04R\tcpuTimeUs\"\xd6\x02\n" +
	"\n" +
	"QueryStats\x12B\n" +
	"\fquery_phases\x18\x01 \x03(\v2\x1f.Ydb.TableStats.QueryPhaseStatsR\vqueryPhases\x12B\n" +
	"\vcompilation\x18\x02 \x01(\v2 .Ydb.TableStats.CompilationStatsR\vcompilation\x12-\n" +
	"\x13process_cpu_time_us\x18\x03 \x01(\x04R\x10processCpuTimeUs\x12\x1d\n" +
	"\n" +
	"query_plan\x18\x04 \x01(\tR\tqueryPlan\x12\x1b\n" +
	"\tquery_ast\x18\x05 \x01(\tR\bqueryAst\x12*\n" +
	"\x11total_duration_us\x18\x06 \x01(\x04R\x0ftotalDurationUs\x12)\n" +
	"\x11total_cpu_time_us\x18\a \x01(\x04R\x0etotalCpuTimeUsBZ\n" +
	"\x0etech.ydb.protoZ=github.com/ydb-platform/ydb-go-genproto/protos/Ydb_TableStats\xf8\x01\x01\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_protos_ydb_query_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_ydb_query_stats_proto_goTypes = []any{
	(*OperationStats)(nil),   // 0: Ydb.TableStats.OperationStats
	(*TableAccessStats)(nil), // 1: Ydb.TableStats.TableAccessStats
	(*QueryPhaseStats)(nil),  // 2: Ydb.TableStats.QueryPhaseStats
	(*CompilationStats)(nil), // 3: Ydb.TableStats.CompilationStats
	(*QueryStats)(nil),       // 4: Ydb.TableStats.QueryStats
}
var file_protos_ydb_query_stats_proto_depIdxs = []int32{
	0, // 0: Ydb.TableStats.TableAccessStats.reads:type_name -> Ydb.TableStats.OperationStats
	0, // 1: Ydb.TableStats.TableAccessStats.updates:type_name -> Ydb.TableStats.OperationStats
	0, // 2: Ydb.TableStats.TableAccessStats.deletes:type_name -> Ydb.TableStats.OperationStats
	1, // 3: Ydb.TableStats.QueryPhaseStats.table_access:type_name -> Ydb.TableStats.TableAccessStats
	2, // 4: Ydb.TableStats.QueryStats.query_phases:type_name -> Ydb.TableStats.QueryPhaseStats
	3, // 5: Ydb.TableStats.QueryStats.compilation:type_name -> Ydb.TableStats.CompilationStats
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_ydb_query_stats_proto_init() }
func file_protos_ydb_query_stats_proto_init() {
	if File_protos_ydb_query_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_query_stats_proto_rawDesc), len(file_protos_ydb_query_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_query_stats_proto_goTypes,
		DependencyIndexes: file_protos_ydb_query_stats_proto_depIdxs,
		MessageInfos:      file_protos_ydb_query_stats_proto_msgTypes,
	}.Build()
	File_protos_ydb_query_stats_proto = out.File
	file_protos_ydb_query_stats_proto_goTypes = nil
	file_protos_ydb_query_stats_proto_depIdxs = nil
}
