// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/ydb_rate_limiter.proto

//go:build !protoopaque

package Ydb_RateLimiter

import (
	Ydb_Operations "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Operations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Settings for hierarchical deficit round robin (HDRR) algorithm.
type HierarchicalDrrSettings struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Resource consumption speed limit.
	// Value is required for root resource.
	// 0 is equivalent to not set.
	// Must be nonnegative.
	MaxUnitsPerSecond *float64 `protobuf:"fixed64,1,opt,name=max_units_per_second,json=maxUnitsPerSecond" json:"max_units_per_second,omitempty"`
	// Maximum burst size of resource consumption across the whole cluster
	// divided by max_units_per_second.
	// Default value is 1.
	// This means that maximum burst size might be equal to max_units_per_second.
	// 0 is equivalent to not set.
	// Must be nonnegative.
	MaxBurstSizeCoefficient *float64 `protobuf:"fixed64,2,opt,name=max_burst_size_coefficient,json=maxBurstSizeCoefficient" json:"max_burst_size_coefficient,omitempty"`
	// Prefetch in local bucket up to prefetch_coefficient*max_units_per_second units (full size).
	// Default value is inherited from parent or 0.2 for root.
	// Disables prefetching if any negative value is set
	// (It is useful to avoid bursts in case of large number of local buckets).
	PrefetchCoefficient *float64 `protobuf:"fixed64,3,opt,name=prefetch_coefficient,json=prefetchCoefficient" json:"prefetch_coefficient,omitempty"`
	// Prefetching starts if there is less than prefetch_watermark fraction of full local bucket left.
	// Default value is inherited from parent or 0.75 for root.
	// Must be nonnegative and less than or equal to 1.
	PrefetchWatermark *float64 `protobuf:"fixed64,4,opt,name=prefetch_watermark,json=prefetchWatermark" json:"prefetch_watermark,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HierarchicalDrrSettings) Reset() {
	*x = HierarchicalDrrSettings{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HierarchicalDrrSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HierarchicalDrrSettings) ProtoMessage() {}

func (x *HierarchicalDrrSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HierarchicalDrrSettings) GetMaxUnitsPerSecond() float64 {
	if x != nil && x.MaxUnitsPerSecond != nil {
		return *x.MaxUnitsPerSecond
	}
	return 0
}

func (x *HierarchicalDrrSettings) GetMaxBurstSizeCoefficient() float64 {
	if x != nil && x.MaxBurstSizeCoefficient != nil {
		return *x.MaxBurstSizeCoefficient
	}
	return 0
}

func (x *HierarchicalDrrSettings) GetPrefetchCoefficient() float64 {
	if x != nil && x.PrefetchCoefficient != nil {
		return *x.PrefetchCoefficient
	}
	return 0
}

func (x *HierarchicalDrrSettings) GetPrefetchWatermark() float64 {
	if x != nil && x.PrefetchWatermark != nil {
		return *x.PrefetchWatermark
	}
	return 0
}

func (x *HierarchicalDrrSettings) SetMaxUnitsPerSecond(v float64) {
	x.MaxUnitsPerSecond = &v
}

func (x *HierarchicalDrrSettings) SetMaxBurstSizeCoefficient(v float64) {
	x.MaxBurstSizeCoefficient = &v
}

func (x *HierarchicalDrrSettings) SetPrefetchCoefficient(v float64) {
	x.PrefetchCoefficient = &v
}

func (x *HierarchicalDrrSettings) SetPrefetchWatermark(v float64) {
	x.PrefetchWatermark = &v
}

func (x *HierarchicalDrrSettings) HasMaxUnitsPerSecond() bool {
	if x == nil {
		return false
	}
	return x.MaxUnitsPerSecond != nil
}

func (x *HierarchicalDrrSettings) HasMaxBurstSizeCoefficient() bool {
	if x == nil {
		return false
	}
	return x.MaxBurstSizeCoefficient != nil
}

func (x *HierarchicalDrrSettings) HasPrefetchCoefficient() bool {
	if x == nil {
		return false
	}
	return x.PrefetchCoefficient != nil
}

func (x *HierarchicalDrrSettings) HasPrefetchWatermark() bool {
	if x == nil {
		return false
	}
	return x.PrefetchWatermark != nil
}

func (x *HierarchicalDrrSettings) ClearMaxUnitsPerSecond() {
	x.MaxUnitsPerSecond = nil
}

func (x *HierarchicalDrrSettings) ClearMaxBurstSizeCoefficient() {
	x.MaxBurstSizeCoefficient = nil
}

func (x *HierarchicalDrrSettings) ClearPrefetchCoefficient() {
	x.PrefetchCoefficient = nil
}

func (x *HierarchicalDrrSettings) ClearPrefetchWatermark() {
	x.PrefetchWatermark = nil
}

type HierarchicalDrrSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Resource consumption speed limit.
	// Value is required for root resource.
	// 0 is equivalent to not set.
	// Must be nonnegative.
	MaxUnitsPerSecond *float64
	// Maximum burst size of resource consumption across the whole cluster
	// divided by max_units_per_second.
	// Default value is 1.
	// This means that maximum burst size might be equal to max_units_per_second.
	// 0 is equivalent to not set.
	// Must be nonnegative.
	MaxBurstSizeCoefficient *float64
	// Prefetch in local bucket up to prefetch_coefficient*max_units_per_second units (full size).
	// Default value is inherited from parent or 0.2 for root.
	// Disables prefetching if any negative value is set
	// (It is useful to avoid bursts in case of large number of local buckets).
	PrefetchCoefficient *float64
	// Prefetching starts if there is less than prefetch_watermark fraction of full local bucket left.
	// Default value is inherited from parent or 0.75 for root.
	// Must be nonnegative and less than or equal to 1.
	PrefetchWatermark *float64
}

func (b0 HierarchicalDrrSettings_builder) Build() *HierarchicalDrrSettings {
	m0 := &HierarchicalDrrSettings{}
	b, x := &b0, m0
	_, _ = b, x
	x.MaxUnitsPerSecond = b.MaxUnitsPerSecond
	x.MaxBurstSizeCoefficient = b.MaxBurstSizeCoefficient
	x.PrefetchCoefficient = b.PrefetchCoefficient
	x.PrefetchWatermark = b.PrefetchWatermark
	return m0
}

// Rate limiter resource description.
type Resource struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Resource path. Elements are separated by slash.
	// The first symbol is not slash.
	// The first element is root resource name.
	// Resource path is the path of resource inside coordination node.
	ResourcePath *string `protobuf:"bytes,1,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Resource_HierarchicalDrr
	Type          isResource_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Resource) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *Resource) GetType() isResource_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Resource) GetHierarchicalDrr() *HierarchicalDrrSettings {
	if x != nil {
		if x, ok := x.Type.(*Resource_HierarchicalDrr); ok {
			return x.HierarchicalDrr
		}
	}
	return nil
}

func (x *Resource) SetResourcePath(v string) {
	x.ResourcePath = &v
}

func (x *Resource) SetHierarchicalDrr(v *HierarchicalDrrSettings) {
	if v == nil {
		x.Type = nil
		return
	}
	x.Type = &Resource_HierarchicalDrr{v}
}

func (x *Resource) HasResourcePath() bool {
	if x == nil {
		return false
	}
	return x.ResourcePath != nil
}

func (x *Resource) HasType() bool {
	if x == nil {
		return false
	}
	return x.Type != nil
}

func (x *Resource) HasHierarchicalDrr() bool {
	if x == nil {
		return false
	}
	_, ok := x.Type.(*Resource_HierarchicalDrr)
	return ok
}

func (x *Resource) ClearResourcePath() {
	x.ResourcePath = nil
}

func (x *Resource) ClearType() {
	x.Type = nil
}

func (x *Resource) ClearHierarchicalDrr() {
	if _, ok := x.Type.(*Resource_HierarchicalDrr); ok {
		x.Type = nil
	}
}

const Resource_Type_not_set_case case_Resource_Type = 0
const Resource_HierarchicalDrr_case case_Resource_Type = 2

func (x *Resource) WhichType() case_Resource_Type {
	if x == nil {
		return Resource_Type_not_set_case
	}
	switch x.Type.(type) {
	case *Resource_HierarchicalDrr:
		return Resource_HierarchicalDrr_case
	default:
		return Resource_Type_not_set_case
	}
}

type Resource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Resource path. Elements are separated by slash.
	// The first symbol is not slash.
	// The first element is root resource name.
	// Resource path is the path of resource inside coordination node.
	ResourcePath *string
	// Fields of oneof Type:
	// Settings for Hierarchical DRR algorithm.
	HierarchicalDrr *HierarchicalDrrSettings
	// -- end of Type
}

func (b0 Resource_builder) Build() *Resource {
	m0 := &Resource{}
	b, x := &b0, m0
	_, _ = b, x
	x.ResourcePath = b.ResourcePath
	if b.HierarchicalDrr != nil {
		x.Type = &Resource_HierarchicalDrr{b.HierarchicalDrr}
	}
	return m0
}

type case_Resource_Type protoreflect.FieldNumber

func (x case_Resource_Type) String() string {
	md := file_protos_ydb_rate_limiter_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isResource_Type interface {
	isResource_Type()
}

type Resource_HierarchicalDrr struct {
	// Settings for Hierarchical DRR algorithm.
	HierarchicalDrr *HierarchicalDrrSettings `protobuf:"bytes,2,opt,name=hierarchical_drr,json=hierarchicalDrr,oneof"`
}

func (*Resource_HierarchicalDrr) isResource_Type() {}

type CreateResourceRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// Resource properties.
	Resource      *Resource `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateResourceRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *CreateResourceRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *CreateResourceRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CreateResourceRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *CreateResourceRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *CreateResourceRequest) SetResource(v *Resource) {
	x.Resource = v
}

func (x *CreateResourceRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *CreateResourceRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *CreateResourceRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return x.Resource != nil
}

func (x *CreateResourceRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *CreateResourceRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *CreateResourceRequest) ClearResource() {
	x.Resource = nil
}

type CreateResourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// Resource properties.
	Resource *Resource
}

func (b0 CreateResourceRequest_builder) Build() *CreateResourceRequest {
	m0 := &CreateResourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.Resource = b.Resource
	return m0
}

type CreateResourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds CreateResourceResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateResourceResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CreateResourceResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *CreateResourceResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *CreateResourceResponse) ClearOperation() {
	x.Operation = nil
}

type CreateResourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds CreateResourceResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 CreateResourceResponse_builder) Build() *CreateResourceResponse {
	m0 := &CreateResourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type CreateResourceResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResult) Reset() {
	*x = CreateResourceResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResult) ProtoMessage() {}

func (x *CreateResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CreateResourceResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CreateResourceResult_builder) Build() *CreateResourceResult {
	m0 := &CreateResourceResult{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AlterResourceRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// New resource properties.
	Resource      *Resource `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterResourceRequest) Reset() {
	*x = AlterResourceRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterResourceRequest) ProtoMessage() {}

func (x *AlterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AlterResourceRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *AlterResourceRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *AlterResourceRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AlterResourceRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *AlterResourceRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *AlterResourceRequest) SetResource(v *Resource) {
	x.Resource = v
}

func (x *AlterResourceRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *AlterResourceRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *AlterResourceRequest) HasResource() bool {
	if x == nil {
		return false
	}
	return x.Resource != nil
}

func (x *AlterResourceRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *AlterResourceRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *AlterResourceRequest) ClearResource() {
	x.Resource = nil
}

type AlterResourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// New resource properties.
	Resource *Resource
}

func (b0 AlterResourceRequest_builder) Build() *AlterResourceRequest {
	m0 := &AlterResourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.Resource = b.Resource
	return m0
}

type AlterResourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds AlterResourceResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterResourceResponse) Reset() {
	*x = AlterResourceResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterResourceResponse) ProtoMessage() {}

func (x *AlterResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AlterResourceResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *AlterResourceResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *AlterResourceResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *AlterResourceResponse) ClearOperation() {
	x.Operation = nil
}

type AlterResourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds AlterResourceResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 AlterResourceResponse_builder) Build() *AlterResourceResponse {
	m0 := &AlterResourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type AlterResourceResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterResourceResult) Reset() {
	*x = AlterResourceResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterResourceResult) ProtoMessage() {}

func (x *AlterResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AlterResourceResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AlterResourceResult_builder) Build() *AlterResourceResult {
	m0 := &AlterResourceResult{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DropResourceRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// Path of resource inside a coordination node.
	ResourcePath  *string `protobuf:"bytes,3,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropResourceRequest) Reset() {
	*x = DropResourceRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropResourceRequest) ProtoMessage() {}

func (x *DropResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DropResourceRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *DropResourceRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *DropResourceRequest) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *DropResourceRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *DropResourceRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *DropResourceRequest) SetResourcePath(v string) {
	x.ResourcePath = &v
}

func (x *DropResourceRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *DropResourceRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *DropResourceRequest) HasResourcePath() bool {
	if x == nil {
		return false
	}
	return x.ResourcePath != nil
}

func (x *DropResourceRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *DropResourceRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *DropResourceRequest) ClearResourcePath() {
	x.ResourcePath = nil
}

type DropResourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// Path of resource inside a coordination node.
	ResourcePath *string
}

func (b0 DropResourceRequest_builder) Build() *DropResourceRequest {
	m0 := &DropResourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.ResourcePath = b.ResourcePath
	return m0
}

type DropResourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds DropResourceResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropResourceResponse) Reset() {
	*x = DropResourceResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropResourceResponse) ProtoMessage() {}

func (x *DropResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DropResourceResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *DropResourceResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *DropResourceResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *DropResourceResponse) ClearOperation() {
	x.Operation = nil
}

type DropResourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds DropResourceResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 DropResourceResponse_builder) Build() *DropResourceResponse {
	m0 := &DropResourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type DropResourceResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropResourceResult) Reset() {
	*x = DropResourceResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropResourceResult) ProtoMessage() {}

func (x *DropResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DropResourceResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DropResourceResult_builder) Build() *DropResourceResult {
	m0 := &DropResourceResult{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListResourcesRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// Path of resource inside a coordination node.
	// May be empty.
	// In that case all root resources will be listed.
	ResourcePath *string `protobuf:"bytes,3,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	// List resources recursively.
	Recursive     *bool `protobuf:"varint,4,opt,name=recursive" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResourcesRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *ListResourcesRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *ListResourcesRequest) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *ListResourcesRequest) GetRecursive() bool {
	if x != nil && x.Recursive != nil {
		return *x.Recursive
	}
	return false
}

func (x *ListResourcesRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *ListResourcesRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *ListResourcesRequest) SetResourcePath(v string) {
	x.ResourcePath = &v
}

func (x *ListResourcesRequest) SetRecursive(v bool) {
	x.Recursive = &v
}

func (x *ListResourcesRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *ListResourcesRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *ListResourcesRequest) HasResourcePath() bool {
	if x == nil {
		return false
	}
	return x.ResourcePath != nil
}

func (x *ListResourcesRequest) HasRecursive() bool {
	if x == nil {
		return false
	}
	return x.Recursive != nil
}

func (x *ListResourcesRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *ListResourcesRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *ListResourcesRequest) ClearResourcePath() {
	x.ResourcePath = nil
}

func (x *ListResourcesRequest) ClearRecursive() {
	x.Recursive = nil
}

type ListResourcesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// Path of resource inside a coordination node.
	// May be empty.
	// In that case all root resources will be listed.
	ResourcePath *string
	// List resources recursively.
	Recursive *bool
}

func (b0 ListResourcesRequest_builder) Build() *ListResourcesRequest {
	m0 := &ListResourcesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.ResourcePath = b.ResourcePath
	x.Recursive = b.Recursive
	return m0
}

type ListResourcesResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds ListResourcesResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResourcesResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ListResourcesResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *ListResourcesResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *ListResourcesResponse) ClearOperation() {
	x.Operation = nil
}

type ListResourcesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds ListResourcesResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 ListResourcesResponse_builder) Build() *ListResourcesResponse {
	m0 := &ListResourcesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type ListResourcesResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ResourcePaths []string               `protobuf:"bytes,1,rep,name=resource_paths,json=resourcePaths" json:"resource_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResult) Reset() {
	*x = ListResourcesResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResult) ProtoMessage() {}

func (x *ListResourcesResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListResourcesResult) GetResourcePaths() []string {
	if x != nil {
		return x.ResourcePaths
	}
	return nil
}

func (x *ListResourcesResult) SetResourcePaths(v []string) {
	x.ResourcePaths = v
}

type ListResourcesResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResourcePaths []string
}

func (b0 ListResourcesResult_builder) Build() *ListResourcesResult {
	m0 := &ListResourcesResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.ResourcePaths = b.ResourcePaths
	return m0
}

type DescribeResourceRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// Path of resource inside a coordination node.
	ResourcePath  *string `protobuf:"bytes,3,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResourceRequest) Reset() {
	*x = DescribeResourceRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceRequest) ProtoMessage() {}

func (x *DescribeResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DescribeResourceRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *DescribeResourceRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *DescribeResourceRequest) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *DescribeResourceRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *DescribeResourceRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *DescribeResourceRequest) SetResourcePath(v string) {
	x.ResourcePath = &v
}

func (x *DescribeResourceRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *DescribeResourceRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *DescribeResourceRequest) HasResourcePath() bool {
	if x == nil {
		return false
	}
	return x.ResourcePath != nil
}

func (x *DescribeResourceRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *DescribeResourceRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *DescribeResourceRequest) ClearResourcePath() {
	x.ResourcePath = nil
}

type DescribeResourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// Path of resource inside a coordination node.
	ResourcePath *string
}

func (b0 DescribeResourceRequest_builder) Build() *DescribeResourceRequest {
	m0 := &DescribeResourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.ResourcePath = b.ResourcePath
	return m0
}

type DescribeResourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds DescribeResourceResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResourceResponse) Reset() {
	*x = DescribeResourceResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceResponse) ProtoMessage() {}

func (x *DescribeResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DescribeResourceResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *DescribeResourceResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *DescribeResourceResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *DescribeResourceResponse) ClearOperation() {
	x.Operation = nil
}

type DescribeResourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds DescribeResourceResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 DescribeResourceResponse_builder) Build() *DescribeResourceResponse {
	m0 := &DescribeResourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type DescribeResourceResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResourceResult) Reset() {
	*x = DescribeResourceResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResourceResult) ProtoMessage() {}

func (x *DescribeResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DescribeResourceResult) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DescribeResourceResult) SetResource(v *Resource) {
	x.Resource = v
}

func (x *DescribeResourceResult) HasResource() bool {
	if x == nil {
		return false
	}
	return x.Resource != nil
}

func (x *DescribeResourceResult) ClearResource() {
	x.Resource = nil
}

type DescribeResourceResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Resource *Resource
}

func (b0 DescribeResourceResult_builder) Build() *DescribeResourceResult {
	m0 := &DescribeResourceResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.Resource = b.Resource
	return m0
}

type AcquireResourceRequest struct {
	state           protoimpl.MessageState          `protogen:"hybrid.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams" json:"operation_params,omitempty"`
	// Path of a coordination node.
	CoordinationNodePath *string `protobuf:"bytes,2,opt,name=coordination_node_path,json=coordinationNodePath" json:"coordination_node_path,omitempty"`
	// Path of resource inside a coordination node.
	ResourcePath *string `protobuf:"bytes,3,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	// Types that are valid to be assigned to Units:
	//
	//	*AcquireResourceRequest_Required
	//	*AcquireResourceRequest_Used
	Units         isAcquireResourceRequest_Units `protobuf_oneof:"units"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResourceRequest) Reset() {
	*x = AcquireResourceRequest{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResourceRequest) ProtoMessage() {}

func (x *AcquireResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AcquireResourceRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *AcquireResourceRequest) GetCoordinationNodePath() string {
	if x != nil && x.CoordinationNodePath != nil {
		return *x.CoordinationNodePath
	}
	return ""
}

func (x *AcquireResourceRequest) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *AcquireResourceRequest) GetUnits() isAcquireResourceRequest_Units {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *AcquireResourceRequest) GetRequired() uint64 {
	if x != nil {
		if x, ok := x.Units.(*AcquireResourceRequest_Required); ok {
			return x.Required
		}
	}
	return 0
}

func (x *AcquireResourceRequest) GetUsed() uint64 {
	if x != nil {
		if x, ok := x.Units.(*AcquireResourceRequest_Used); ok {
			return x.Used
		}
	}
	return 0
}

func (x *AcquireResourceRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	x.OperationParams = v
}

func (x *AcquireResourceRequest) SetCoordinationNodePath(v string) {
	x.CoordinationNodePath = &v
}

func (x *AcquireResourceRequest) SetResourcePath(v string) {
	x.ResourcePath = &v
}

func (x *AcquireResourceRequest) SetRequired(v uint64) {
	x.Units = &AcquireResourceRequest_Required{v}
}

func (x *AcquireResourceRequest) SetUsed(v uint64) {
	x.Units = &AcquireResourceRequest_Used{v}
}

func (x *AcquireResourceRequest) HasOperationParams() bool {
	if x == nil {
		return false
	}
	return x.OperationParams != nil
}

func (x *AcquireResourceRequest) HasCoordinationNodePath() bool {
	if x == nil {
		return false
	}
	return x.CoordinationNodePath != nil
}

func (x *AcquireResourceRequest) HasResourcePath() bool {
	if x == nil {
		return false
	}
	return x.ResourcePath != nil
}

func (x *AcquireResourceRequest) HasUnits() bool {
	if x == nil {
		return false
	}
	return x.Units != nil
}

func (x *AcquireResourceRequest) HasRequired() bool {
	if x == nil {
		return false
	}
	_, ok := x.Units.(*AcquireResourceRequest_Required)
	return ok
}

func (x *AcquireResourceRequest) HasUsed() bool {
	if x == nil {
		return false
	}
	_, ok := x.Units.(*AcquireResourceRequest_Used)
	return ok
}

func (x *AcquireResourceRequest) ClearOperationParams() {
	x.OperationParams = nil
}

func (x *AcquireResourceRequest) ClearCoordinationNodePath() {
	x.CoordinationNodePath = nil
}

func (x *AcquireResourceRequest) ClearResourcePath() {
	x.ResourcePath = nil
}

func (x *AcquireResourceRequest) ClearUnits() {
	x.Units = nil
}

func (x *AcquireResourceRequest) ClearRequired() {
	if _, ok := x.Units.(*AcquireResourceRequest_Required); ok {
		x.Units = nil
	}
}

func (x *AcquireResourceRequest) ClearUsed() {
	if _, ok := x.Units.(*AcquireResourceRequest_Used); ok {
		x.Units = nil
	}
}

const AcquireResourceRequest_Units_not_set_case case_AcquireResourceRequest_Units = 0
const AcquireResourceRequest_Required_case case_AcquireResourceRequest_Units = 4
const AcquireResourceRequest_Used_case case_AcquireResourceRequest_Units = 5

func (x *AcquireResourceRequest) WhichUnits() case_AcquireResourceRequest_Units {
	if x == nil {
		return AcquireResourceRequest_Units_not_set_case
	}
	switch x.Units.(type) {
	case *AcquireResourceRequest_Required:
		return AcquireResourceRequest_Required_case
	case *AcquireResourceRequest_Used:
		return AcquireResourceRequest_Used_case
	default:
		return AcquireResourceRequest_Units_not_set_case
	}
}

type AcquireResourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OperationParams *Ydb_Operations.OperationParams
	// Path of a coordination node.
	CoordinationNodePath *string
	// Path of resource inside a coordination node.
	ResourcePath *string
	// Fields of oneof Units:
	// Request resource's units for usage.
	Required *uint64
	// Actually used resource's units by client.
	Used *uint64
	// -- end of Units
}

func (b0 AcquireResourceRequest_builder) Build() *AcquireResourceRequest {
	m0 := &AcquireResourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.OperationParams = b.OperationParams
	x.CoordinationNodePath = b.CoordinationNodePath
	x.ResourcePath = b.ResourcePath
	if b.Required != nil {
		x.Units = &AcquireResourceRequest_Required{*b.Required}
	}
	if b.Used != nil {
		x.Units = &AcquireResourceRequest_Used{*b.Used}
	}
	return m0
}

type case_AcquireResourceRequest_Units protoreflect.FieldNumber

func (x case_AcquireResourceRequest_Units) String() string {
	md := file_protos_ydb_rate_limiter_proto_msgTypes[17].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAcquireResourceRequest_Units interface {
	isAcquireResourceRequest_Units()
}

type AcquireResourceRequest_Required struct {
	// Request resource's units for usage.
	Required uint64 `protobuf:"varint,4,opt,name=required,oneof"`
}

type AcquireResourceRequest_Used struct {
	// Actually used resource's units by client.
	Used uint64 `protobuf:"varint,5,opt,name=used,oneof"`
}

func (*AcquireResourceRequest_Required) isAcquireResourceRequest_Units() {}

func (*AcquireResourceRequest_Used) isAcquireResourceRequest_Units() {}

type AcquireResourceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Holds AcquireResourceResult in case of successful call.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResourceResponse) Reset() {
	*x = AcquireResourceResponse{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResourceResponse) ProtoMessage() {}

func (x *AcquireResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AcquireResourceResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *AcquireResourceResponse) SetOperation(v *Ydb_Operations.Operation) {
	x.Operation = v
}

func (x *AcquireResourceResponse) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.Operation != nil
}

func (x *AcquireResourceResponse) ClearOperation() {
	x.Operation = nil
}

type AcquireResourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Holds AcquireResourceResult in case of successful call.
	Operation *Ydb_Operations.Operation
}

func (b0 AcquireResourceResponse_builder) Build() *AcquireResourceResponse {
	m0 := &AcquireResourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Operation = b.Operation
	return m0
}

type AcquireResourceResult struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResourceResult) Reset() {
	*x = AcquireResourceResult{}
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResourceResult) ProtoMessage() {}

func (x *AcquireResourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_rate_limiter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AcquireResourceResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AcquireResourceResult_builder) Build() *AcquireResourceResult {
	m0 := &AcquireResourceResult{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_protos_ydb_rate_limiter_proto protoreflect.FileDescriptor

const file_protos_ydb_rate_limiter_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/ydb_rate_limiter.proto\x12\x0fYdb.RateLimiter\x1a\x1aprotos/ydb_operation.proto\x1a!google/protobuf/go_features.proto\"\xe9\x01\n" +
	"\x17HierarchicalDrrSettings\x12/\n" +
	"\x14max_units_per_second\x18\x01 \x01(\x01R\x11maxUnitsPerSecond\x12;\n" +
	"\x1amax_burst_size_coefficient\x18\x02 \x01(\x01R\x17maxBurstSizeCoefficient\x121\n" +
	"\x14prefetch_coefficient\x18\x03 \x01(\x01R\x13prefetchCoefficient\x12-\n" +
	"\x12prefetch_watermark\x18\x04 \x01(\x01R\x11prefetchWatermark\"\x8e\x01\n" +
	"\bResource\x12#\n" +
	"\rresource_path\x18\x01 \x01(\tR\fresourcePath\x12U\n" +
	"\x10hierarchical_drr\x18\x02 \x01(\v2(.Ydb.RateLimiter.HierarchicalDrrSettingsH\x00R\x0fhierarchicalDrrB\x06\n" +
	"\x04type\"\xd0\x01\n" +
	"\x15CreateResourceRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x125\n" +
	"\bresource\x18\x03 \x01(\v2\x19.Ydb.RateLimiter.ResourceR\bresource\"Q\n" +
	"\x16CreateResourceResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x16\n" +
	"\x14CreateResourceResult\"\xcf\x01\n" +
	"\x14AlterResourceRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x125\n" +
	"\bresource\x18\x03 \x01(\v2\x19.Ydb.RateLimiter.ResourceR\bresource\"P\n" +
	"\x15AlterResourceResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x15\n" +
	"\x13AlterResourceResult\"\xbc\x01\n" +
	"\x13DropResourceRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x12#\n" +
	"\rresource_path\x18\x03 \x01(\tR\fresourcePath\"O\n" +
	"\x14DropResourceResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x14\n" +
	"\x12DropResourceResult\"\xdb\x01\n" +
	"\x14ListResourcesRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x12#\n" +
	"\rresource_path\x18\x03 \x01(\tR\fresourcePath\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursive\"P\n" +
	"\x15ListResourcesResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"<\n" +
	"\x13ListResourcesResult\x12%\n" +
	"\x0eresource_paths\x18\x01 \x03(\tR\rresourcePaths\"\xc0\x01\n" +
	"\x17DescribeResourceRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x12#\n" +
	"\rresource_path\x18\x03 \x01(\tR\fresourcePath\"S\n" +
	"\x18DescribeResourceResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"O\n" +
	"\x16DescribeResourceResult\x125\n" +
	"\bresource\x18\x01 \x01(\v2\x19.Ydb.RateLimiter.ResourceR\bresource\"\xfc\x01\n" +
	"\x16AcquireResourceRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x124\n" +
	"\x16coordination_node_path\x18\x02 \x01(\tR\x14coordinationNodePath\x12#\n" +
	"\rresource_path\x18\x03 \x01(\tR\fresourcePath\x12\x1c\n" +
	"\brequired\x18\x04 \x01(\x04H\x00R\brequired\x12\x14\n" +
	"\x04used\x18\x05 \x01(\x04H\x00R\x04usedB\a\n" +
	"\x05units\"R\n" +
	"\x17AcquireResourceResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"\x17\n" +
	"\x15AcquireResourceResultB}\n" +
	"\x1btech.ydb.proto.rate_limiterB\x11RateLimiterProtosP\x01Z>github.com/ydb-platform/ydb-go-genproto/protos/Ydb_RateLimiter\xf8\x01\x01\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_protos_ydb_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_protos_ydb_rate_limiter_proto_goTypes = []any{
	(*HierarchicalDrrSettings)(nil),        // 0: Ydb.RateLimiter.HierarchicalDrrSettings
	(*Resource)(nil),                       // 1: Ydb.RateLimiter.Resource
	(*CreateResourceRequest)(nil),          // 2: Ydb.RateLimiter.CreateResourceRequest
	(*CreateResourceResponse)(nil),         // 3: Ydb.RateLimiter.CreateResourceResponse
	(*CreateResourceResult)(nil),           // 4: Ydb.RateLimiter.CreateResourceResult
	(*AlterResourceRequest)(nil),           // 5: Ydb.RateLimiter.AlterResourceRequest
	(*AlterResourceResponse)(nil),          // 6: Ydb.RateLimiter.AlterResourceResponse
	(*AlterResourceResult)(nil),            // 7: Ydb.RateLimiter.AlterResourceResult
	(*DropResourceRequest)(nil),            // 8: Ydb.RateLimiter.DropResourceRequest
	(*DropResourceResponse)(nil),           // 9: Ydb.RateLimiter.DropResourceResponse
	(*DropResourceResult)(nil),             // 10: Ydb.RateLimiter.DropResourceResult
	(*ListResourcesRequest)(nil),           // 11: Ydb.RateLimiter.ListResourcesRequest
	(*ListResourcesResponse)(nil),          // 12: Ydb.RateLimiter.ListResourcesResponse
	(*ListResourcesResult)(nil),            // 13: Ydb.RateLimiter.ListResourcesResult
	(*DescribeResourceRequest)(nil),        // 14: Ydb.RateLimiter.DescribeResourceRequest
	(*DescribeResourceResponse)(nil),       // 15: Ydb.RateLimiter.DescribeResourceResponse
	(*DescribeResourceResult)(nil),         // 16: Ydb.RateLimiter.DescribeResourceResult
	(*AcquireResourceRequest)(nil),         // 17: Ydb.RateLimiter.AcquireResourceRequest
	(*AcquireResourceResponse)(nil),        // 18: Ydb.RateLimiter.AcquireResourceResponse
	(*AcquireResourceResult)(nil),          // 19: Ydb.RateLimiter.AcquireResourceResult
	(*Ydb_Operations.OperationParams)(nil), // 20: Ydb.Operations.OperationParams
	(*Ydb_Operations.Operation)(nil),       // 21: Ydb.Operations.Operation
}
var file_protos_ydb_rate_limiter_proto_depIdxs = []int32{
	0,  // 0: Ydb.RateLimiter.Resource.hierarchical_drr:type_name -> Ydb.RateLimiter.HierarchicalDrrSettings
	20, // 1: Ydb.RateLimiter.CreateResourceRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	1,  // 2: Ydb.RateLimiter.CreateResourceRequest.resource:type_name -> Ydb.RateLimiter.Resource
	21, // 3: Ydb.RateLimiter.CreateResourceResponse.operation:type_name -> Ydb.Operations.Operation
	20, // 4: Ydb.RateLimiter.AlterResourceRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	1,  // 5: Ydb.RateLimiter.AlterResourceRequest.resource:type_name -> Ydb.RateLimiter.Resource
	21, // 6: Ydb.RateLimiter.AlterResourceResponse.operation:type_name -> Ydb.Operations.Operation
	20, // 7: Ydb.RateLimiter.DropResourceRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	21, // 8: Ydb.RateLimiter.DropResourceResponse.operation:type_name -> Ydb.Operations.Operation
	20, // 9: Ydb.RateLimiter.ListResourcesRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	21, // 10: Ydb.RateLimiter.ListResourcesResponse.operation:type_name -> Ydb.Operations.Operation
	20, // 11: Ydb.RateLimiter.DescribeResourceRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	21, // 12: Ydb.RateLimiter.DescribeResourceResponse.operation:type_name -> Ydb.Operations.Operation
	1,  // 13: Ydb.RateLimiter.DescribeResourceResult.resource:type_name -> Ydb.RateLimiter.Resource
	20, // 14: Ydb.RateLimiter.AcquireResourceRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	21, // 15: Ydb.RateLimiter.AcquireResourceResponse.operation:type_name -> Ydb.Operations.Operation
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protos_ydb_rate_limiter_proto_init() }
func file_protos_ydb_rate_limiter_proto_init() {
	if File_protos_ydb_rate_limiter_proto != nil {
		return
	}
	file_protos_ydb_rate_limiter_proto_msgTypes[1].OneofWrappers = []any{
		(*Resource_HierarchicalDrr)(nil),
	}
	file_protos_ydb_rate_limiter_proto_msgTypes[17].OneofWrappers = []any{
		(*AcquireResourceRequest_Required)(nil),
		(*AcquireResourceRequest_Used)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_rate_limiter_proto_rawDesc), len(file_protos_ydb_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_rate_limiter_proto_goTypes,
		DependencyIndexes: file_protos_ydb_rate_limiter_proto_depIdxs,
		MessageInfos:      file_protos_ydb_rate_limiter_proto_msgTypes,
	}.Build()
	File_protos_ydb_rate_limiter_proto = out.File
	file_protos_ydb_rate_limiter_proto_goTypes = nil
	file_protos_ydb_rate_limiter_proto_depIdxs = nil
}
