// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: ydb_operation_v1.proto

package Ydb_Operation_V1

import (
	Ydb_Operations "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Operations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ydb_operation_v1_proto protoreflect.FileDescriptor

const file_ydb_operation_v1_proto_rawDesc = "" +
	"\n" +
	"\x16ydb_operation_v1.proto\x12\x10Ydb.Operation.V1\x1a\x1aprotos/ydb_operation.proto2\x96\x03\n" +
	"\x10OperationService\x12Y\n" +
	"\fGetOperation\x12#.Ydb.Operations.GetOperationRequest\x1a$.Ydb.Operations.GetOperationResponse\x12b\n" +
	"\x0fCancelOperation\x12&.Ydb.Operations.CancelOperationRequest\x1a'.Ydb.Operations.CancelOperationResponse\x12b\n" +
	"\x0fForgetOperation\x12&.Ydb.Operations.ForgetOperationRequest\x1a'.Ydb.Operations.ForgetOperationResponse\x12_\n" +
	"\x0eListOperations\x12%.Ydb.Operations.ListOperationsRequest\x1a&.Ydb.Operations.ListOperationsResponseBW\n" +
	"\x1btech.ydb.proto.operation.v1Z8github.com/ydb-platform/ydb-go-genproto/Ydb_Operation_V1b\x06proto3"

var file_ydb_operation_v1_proto_goTypes = []any{
	(*Ydb_Operations.GetOperationRequest)(nil),     // 0: Ydb.Operations.GetOperationRequest
	(*Ydb_Operations.CancelOperationRequest)(nil),  // 1: Ydb.Operations.CancelOperationRequest
	(*Ydb_Operations.ForgetOperationRequest)(nil),  // 2: Ydb.Operations.ForgetOperationRequest
	(*Ydb_Operations.ListOperationsRequest)(nil),   // 3: Ydb.Operations.ListOperationsRequest
	(*Ydb_Operations.GetOperationResponse)(nil),    // 4: Ydb.Operations.GetOperationResponse
	(*Ydb_Operations.CancelOperationResponse)(nil), // 5: Ydb.Operations.CancelOperationResponse
	(*Ydb_Operations.ForgetOperationResponse)(nil), // 6: Ydb.Operations.ForgetOperationResponse
	(*Ydb_Operations.ListOperationsResponse)(nil),  // 7: Ydb.Operations.ListOperationsResponse
}
var file_ydb_operation_v1_proto_depIdxs = []int32{
	0, // 0: Ydb.Operation.V1.OperationService.GetOperation:input_type -> Ydb.Operations.GetOperationRequest
	1, // 1: Ydb.Operation.V1.OperationService.CancelOperation:input_type -> Ydb.Operations.CancelOperationRequest
	2, // 2: Ydb.Operation.V1.OperationService.ForgetOperation:input_type -> Ydb.Operations.ForgetOperationRequest
	3, // 3: Ydb.Operation.V1.OperationService.ListOperations:input_type -> Ydb.Operations.ListOperationsRequest
	4, // 4: Ydb.Operation.V1.OperationService.GetOperation:output_type -> Ydb.Operations.GetOperationResponse
	5, // 5: Ydb.Operation.V1.OperationService.CancelOperation:output_type -> Ydb.Operations.CancelOperationResponse
	6, // 6: Ydb.Operation.V1.OperationService.ForgetOperation:output_type -> Ydb.Operations.ForgetOperationResponse
	7, // 7: Ydb.Operation.V1.OperationService.ListOperations:output_type -> Ydb.Operations.ListOperationsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ydb_operation_v1_proto_init() }
func file_ydb_operation_v1_proto_init() {
	if File_ydb_operation_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ydb_operation_v1_proto_rawDesc), len(file_ydb_operation_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ydb_operation_v1_proto_goTypes,
		DependencyIndexes: file_ydb_operation_v1_proto_depIdxs,
	}.Build()
	File_ydb_operation_v1_proto = out.File
	file_ydb_operation_v1_proto_goTypes = nil
	file_ydb_operation_v1_proto_depIdxs = nil
}
