// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: protos/ydb_auth.proto

package Ydb_Auth

import (
	Ydb_Operations "github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Operations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	OperationParams *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	User            string                          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password        string                          `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_protos_ydb_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_protos_ydb_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if x != nil {
		return x.OperationParams
	}
	return nil
}

func (x *LoginRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// After successfull completion must contain LoginResult.
	Operation     *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_protos_ydb_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_protos_ydb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetOperation() *Ydb_Operations.Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type LoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	mi := &file_protos_ydb_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ydb_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_protos_ydb_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_protos_ydb_auth_proto protoreflect.FileDescriptor

const file_protos_ydb_auth_proto_rawDesc = "" +
	"\n" +
	"\x15protos/ydb_auth.proto\x12\bYdb.Auth\x1a\x1aprotos/ydb_operation.proto\"\x8a\x01\n" +
	"\fLoginRequest\x12J\n" +
	"\x10operation_params\x18\x01 \x01(\v2\x1f.Ydb.Operations.OperationParamsR\x0foperationParams\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"H\n" +
	"\rLoginResponse\x127\n" +
	"\toperation\x18\x01 \x01(\v2\x19.Ydb.Operations.OperationR\toperation\"#\n" +
	"\vLoginResult\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenBQ\n" +
	"\x13tech.ydb.proto.authZ7github.com/ydb-platform/ydb-go-genproto/protos/Ydb_Auth\xf8\x01\x01b\x06proto3"

var (
	file_protos_ydb_auth_proto_rawDescOnce sync.Once
	file_protos_ydb_auth_proto_rawDescData []byte
)

func file_protos_ydb_auth_proto_rawDescGZIP() []byte {
	file_protos_ydb_auth_proto_rawDescOnce.Do(func() {
		file_protos_ydb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_ydb_auth_proto_rawDesc), len(file_protos_ydb_auth_proto_rawDesc)))
	})
	return file_protos_ydb_auth_proto_rawDescData
}

var file_protos_ydb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_ydb_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                   // 0: Ydb.Auth.LoginRequest
	(*LoginResponse)(nil),                  // 1: Ydb.Auth.LoginResponse
	(*LoginResult)(nil),                    // 2: Ydb.Auth.LoginResult
	(*Ydb_Operations.OperationParams)(nil), // 3: Ydb.Operations.OperationParams
	(*Ydb_Operations.Operation)(nil),       // 4: Ydb.Operations.Operation
}
var file_protos_ydb_auth_proto_depIdxs = []int32{
	3, // 0: Ydb.Auth.LoginRequest.operation_params:type_name -> Ydb.Operations.OperationParams
	4, // 1: Ydb.Auth.LoginResponse.operation:type_name -> Ydb.Operations.Operation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_ydb_auth_proto_init() }
func file_protos_ydb_auth_proto_init() {
	if File_protos_ydb_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_ydb_auth_proto_rawDesc), len(file_protos_ydb_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ydb_auth_proto_goTypes,
		DependencyIndexes: file_protos_ydb_auth_proto_depIdxs,
		MessageInfos:      file_protos_ydb_auth_proto_msgTypes,
	}.Build()
	File_protos_ydb_auth_proto = out.File
	file_protos_ydb_auth_proto_goTypes = nil
	file_protos_ydb_auth_proto_depIdxs = nil
}
